PRAGMA foreign_keys = ON;
BEGIN;

DELETE FROM channel_conversation_thread_replies
WHERE conversation_id LIKE 'biz_%';

INSERT INTO channel_conversation_thread_replies (
    conversation_id,
    root_step_order,
    reply_order,
    username,
    offset_minutes,
    message
) VALUES
-- Project Aurora
('biz_aurora_release_scope', 1, 1, 'user07', 3, '認識は合っています。通知設定は確認環境への反映待ちです。'),
('biz_aurora_release_scope', 1, 2, 'user14', 7, '検索改善は回帰試験まで完了しており、追加の懸念はありません。'),
('biz_aurora_release_scope', 1, 3, 'user01', 12, 'プロフィール画面を含めないことも進行表へ明記します。'),
('biz_aurora_release_scope', 1, 4, 'user07', 18, '変更点の案内も検索と通知の二項目に絞りました。'),
('biz_aurora_release_scope', 1, 5, 'user14', 25, '通知設定は夕方までに結果を共有できます'),
('biz_aurora_release_scope', 1, 6, 'user01', 33, '未完了項目が一つなら、明日の判定会は予定どおり行います'),
('biz_aurora_release_scope', 1, 7, 'user07', 42, '確認結果と案内文の内容がずれないよう、試験が済んだ時点でもう一度共有します。判定前に一緒に最終確認しましょう。'),

('biz_aurora_data_migration', 1, 1, 'user22', 3, '差分は解消しました。空欄データの扱いが原因でした。'),
('biz_aurora_data_migration', 1, 2, 'user08', 7, '補正した12件は、サポート側でも照合したいです。'),
('biz_aurora_data_migration', 1, 3, 'user14', 12, '個人情報を含めず、管理番号だけの一覧にしてください。'),
('biz_aurora_data_migration', 1, 4, 'user22', 18, '管理番号と補正理由だけを載せた一覧を作成しました'),
('biz_aurora_data_migration', 1, 5, 'user08', 25, '確認できました。問い合わせ時の説明にも使えます。'),
('biz_aurora_data_migration', 1, 6, 'user22', 33, '次回は同じ補正を自動で適用するようにします'),
('biz_aurora_data_migration', 1, 7, 'user14', 42, '一覧で照合できることも分かったので、次は手作業なしで再実行しましょう。件数が一致したら補正ルールを確定します。'),

('biz_aurora_mobile_check', 1, 1, 'user18', 3, '縦向きの二サイズでは崩れが直っていました。'),
('biz_aurora_mobile_check', 1, 2, 'user32', 7, '横向きだけ最大幅の指定が残っているようです。'),
('biz_aurora_mobile_check', 1, 3, 'user05', 12, '長い見出しの折り返しも一緒に確認してください。'),
('biz_aurora_mobile_check', 1, 4, 'user32', 18, '最大幅を共通値へ直し、確認環境へ反映しました。'),
('biz_aurora_mobile_check', 1, 5, 'user18', 25, '横向きと長い見出しの両方で問題ありません'),
('biz_aurora_mobile_check', 1, 6, 'user05', 33, '試験表に端末サイズと結果を残しておきます'),
('biz_aurora_mobile_check', 1, 7, 'user32', 42, '確認してもらった三サイズと修正理由を差分へ添えました。レビューで別の端末条件が出たら、同じ試験表で追加確認します。'),

('biz_aurora_metrics_review', 1, 1, 'user26', 3, '利用開始率、検索成功率、翌日再訪率を候補にしています。'),
('biz_aurora_metrics_review', 1, 2, 'user35', 7, '検索成功は結果を表示した時点ではなくクリック時点でしょうか。'),
('biz_aurora_metrics_review', 1, 3, 'user12', 12, '操作につながったかを見たいので、クリック時点がよさそうです。'),
('biz_aurora_metrics_review', 1, 4, 'user26', 18, 'その定義なら三指標とも毎日同じ条件で集計できます。'),
('biz_aurora_metrics_review', 1, 5, 'user35', 25, '集計表に定義の注記を付けておきます'),
('biz_aurora_metrics_review', 1, 6, 'user12', 33, '朝会では数値と前日差だけを確認しましょう'),
('biz_aurora_metrics_review', 1, 7, 'user26', 42, '明日分から同じ定義で自動更新されます。朝会で判断しづらい点があれば、指標を増やす前に三人で定義を見直しましょう。'),

('biz_aurora_launch_decision', 1, 1, 'user14', 3, '性能試験と復旧手順は完了しています。'),
('biz_aurora_launch_decision', 1, 2, 'user08', 7, '問い合わせ通知の経路を最後に確認しています。'),
('biz_aurora_launch_decision', 1, 3, 'user03', 12, '通知確認が終われば、公開を止める要因はありません。'),
('biz_aurora_launch_decision', 1, 4, 'user08', 18, 'フォーム送信から担当への通知まで正常でした。'),
('biz_aurora_launch_decision', 1, 5, 'user14', 25, '公開後の監視と切り戻し担当も決めています'),
('biz_aurora_launch_decision', 1, 6, 'user03', 33, 'では予定どおり明朝に公開する判断とします'),
('biz_aurora_launch_decision', 1, 7, 'user08', 42, '案内文を予約しました。公開直後は監視結果も見ながら問い合わせを確認するので、異常の兆候があれば同じ判断材料をここへ集めましょう。'),

-- Project Phoenix
('biz_phoenix_sprint_plan', 1, 1, 'user15', 3, '認証改善は実装五日と回帰試験二日を見込んでいます。'),
('biz_phoenix_sprint_plan', 1, 2, 'user23', 7, '画面側は通常系からなら先に着手できます。'),
('biz_phoenix_sprint_plan', 1, 3, 'user02', 12, 'エラー文言だけ今日中に先行して確定します。'),
('biz_phoenix_sprint_plan', 1, 4, 'user15', 18, '依存関係を作業表へ反映すると余裕日は一日です。'),
('biz_phoenix_sprint_plan', 1, 5, 'user23', 25, '異常系は認証側の応答が揃ってから進めます'),
('biz_phoenix_sprint_plan', 1, 6, 'user02', 33, 'その順序で優先度を確定し、他の改善は次へ送ります'),
('biz_phoenix_sprint_plan', 1, 7, 'user15', 42, '担当者と依存する期限を更新しました。明日は通常系から着手し、異常系の応答例が揃った時点で進め方をもう一度合わせます。'),

('biz_phoenix_accessibility', 1, 1, 'user31', 3, 'こちらでもモーダルを閉じるとページ先頭へ移動しました。'),
('biz_phoenix_accessibility', 1, 2, 'user17', 7, '共通部品なので、同じ部品を使う画面も確認が必要です。'),
('biz_phoenix_accessibility', 1, 3, 'user11', 12, 'キーボードと画面読み上げの両方で試しましょう。'),
('biz_phoenix_accessibility', 1, 4, 'user31', 18, '閉じる前の操作元を記録して戻す修正を入れました。'),
('biz_phoenix_accessibility', 1, 5, 'user17', 25, '影響する四画面へ共通修正が反映されています'),
('biz_phoenix_accessibility', 1, 6, 'user11', 33, '四画面とも操作位置が維持されることを確認しました'),
('biz_phoenix_accessibility', 1, 7, 'user31', 42, 'キーボードと読み上げの結果を同じ試験表へ残します。四画面で差が出た場合は、共通修正を閉じる前に相談させてください。'),

('biz_phoenix_api_contract', 1, 1, 'user28', 3, '追加項目なので既存の画面表示には影響しません。'),
('biz_phoenix_api_contract', 1, 2, 'user33', 7, '値がない場合は空文字と項目省略のどちらでしょうか。'),
('biz_phoenix_api_contract', 1, 3, 'user06', 12, '項目省略です。仕様書にも省略可能と記載します。'),
('biz_phoenix_api_contract', 1, 4, 'user28', 18, '両方の応答例を用意して画面側で確認します。'),
('biz_phoenix_api_contract', 1, 5, 'user33', 25, '試験データに省略された例を追加しました'),
('biz_phoenix_api_contract', 1, 6, 'user28', 33, '既存表示と新しい状態表示のどちらも正常でした'),
('biz_phoenix_api_contract', 1, 7, 'user06', 42, '画面側の確認結果も取り込んで契約試験を更新しました。ほかの利用側への影響がないことを一緒に確認してから次の版へ含めます。'),

('biz_phoenix_incident_drill', 1, 1, 'user37', 3, '監視通知を受け、担当が事象を宣言した時点を開始にします。'),
('biz_phoenix_incident_drill', 1, 2, 'user25', 7, '利用者への第一報は開始から15分以内でよいですか。'),
('biz_phoenix_incident_drill', 1, 3, 'user19', 12, 'はい。原因不明でも影響範囲と次回更新時刻を伝えます。'),
('biz_phoenix_incident_drill', 1, 4, 'user37', 18, '判断担当と調査担当を分けた役割表を用意しました。'),
('biz_phoenix_incident_drill', 1, 5, 'user25', 25, '記録には連絡時刻と判断理由も残します'),
('biz_phoenix_incident_drill', 1, 6, 'user19', 33, '復旧だけでなく、案内文作成まで通して確認しましょう'),
('biz_phoenix_incident_drill', 1, 7, 'user37', 42, '判断時刻と案内作成まで追える確認表を準備しました。訓練後は遅れた工程を責めるのではなく、役割や手順で改善できる点を話しましょう。'),

('biz_phoenix_retrospective', 1, 1, 'user21', 3, 'レビュー待ちが後半に集中した点を扱いたいです。'),
('biz_phoenix_retrospective', 1, 2, 'user34', 7, '依頼時に確認観点が不足していたことも原因だと思います。'),
('biz_phoenix_retrospective', 1, 3, 'user09', 12, '依頼用の確認欄を設ける案で整理しましょう。'),
('biz_phoenix_retrospective', 1, 4, 'user21', 18, 'レビュー担当を前日に決めると偏りも防げそうです。'),
('biz_phoenix_retrospective', 1, 5, 'user34', 25, '確認欄と事前割り当てを次回の試行項目にします'),
('biz_phoenix_retrospective', 1, 6, 'user09', 33, '効果を見るため、待ち時間も同じ方法で計測します'),
('biz_phoenix_retrospective', 1, 7, 'user21', 42, '二つの改善策と待ち時間の測り方を記録しました。次回、依頼側と確認側のどちらかに負担が偏ったら早めに調整しましょう。'),

-- Sales
('biz_sales_discovery', 1, 1, 'user20', 3, '申請作業の重複と進捗の見えにくさが主な課題です。'),
('biz_sales_discovery', 1, 2, 'user30', 7, '現状の流れを先に聞いてからデモを見せたいです。'),
('biz_sales_discovery', 1, 3, 'user04', 12, 'デモは通知機能を中心に五分へ絞りましょう。'),
('biz_sales_discovery', 1, 4, 'user20', 18, '利用人数と承認段階を確認する質問も追加します。'),
('biz_sales_discovery', 1, 5, 'user30', 25, '先方の回答に応じて見せる画面を二通り用意します'),
('biz_sales_discovery', 1, 6, 'user04', 33, '説明より聞き取りの時間を長く取る進行にします'),
('biz_sales_discovery', 1, 7, 'user20', 42, '質問項目と役割分担を共有しました。先方の話が想定と違った場合はデモを無理に進めず、その場で聞き取り中心へ切り替えましょう。'),

('biz_sales_proposal_revision', 1, 1, 'user27', 3, '削減時間を担当業務ごとに分けて再計算します。'),
('biz_sales_proposal_revision', 1, 2, 'user16', 7, '導入初月は習熟期間として効果を低めに置きたいです。'),
('biz_sales_proposal_revision', 1, 3, 'user10', 12, '初月を半分として、前提を注記へ明記しましょう。'),
('biz_sales_proposal_revision', 1, 4, 'user27', 18, '再計算すると回収時期は一か月後ろになります。'),
('biz_sales_proposal_revision', 1, 5, 'user16', 25, '控えめな試算でも効果は説明できる範囲です'),
('biz_sales_proposal_revision', 1, 6, 'user10', 33, '数字の根拠が追えるので、この前提を採用します'),
('biz_sales_proposal_revision', 1, 7, 'user27', 42, '表とグラフを控えめな同じ前提へ揃えました。説明時に先方の実績値が分かれば、三人で置き換えて再試算できるようにしてあります。'),

('biz_sales_security_answers', 1, 1, 'user36', 3, '認証と監査記録は回答済みで、保管期間を確認中です。'),
('biz_sales_security_answers', 1, 2, 'user24', 7, '契約終了後の削除手順も合わせて説明してください。'),
('biz_sales_security_answers', 1, 3, 'user13', 12, '標準条件と個別相談が必要な条件を分けたいです。'),
('biz_sales_security_answers', 1, 4, 'user36', 18, '標準期間と削除申請の流れを運用担当へ確認しました。'),
('biz_sales_security_answers', 1, 5, 'user24', 25, '回答できない箇所は確認先と予定日を明記しましょう'),
('biz_sales_security_answers', 1, 6, 'user13', 33, '全項目に根拠か確認予定が入りました'),
('biz_sales_security_answers', 1, 7, 'user36', 42, '根拠と確認予定を分けた最終版にまとめました。送付前に先方の意図とずれていないか営業側にも見てもらい、明朝に回答します。'),

('biz_sales_trial_followup', 1, 1, 'user04', 3, '検索は好評ですが、管理者が権限設定で迷っています。'),
('biz_sales_trial_followup', 1, 2, 'user30', 7, '役割別の設定例を見せると理解しやすそうです。'),
('biz_sales_trial_followup', 1, 3, 'user20', 12, '利用記録から実際に使われた機能も確認します。'),
('biz_sales_trial_followup', 1, 4, 'user04', 18, '次回の質問を権限、検索、共有の三点に絞りました。'),
('biz_sales_trial_followup', 1, 5, 'user30', 25, '権限の雛形を二種類用意して操作してもらいましょう'),
('biz_sales_trial_followup', 1, 6, 'user20', 33, '使われていない機能の説明は今回は省きます'),
('biz_sales_trial_followup', 1, 7, 'user04', 42, '三つの質問を先方へ送りました。回答に合わせて権限の雛形を選び、合わなければその理由から一緒に設定を組み直します。'),

('biz_sales_handoff', 1, 1, 'user08', 3, '利用部門と開始希望日は確認済みで、管理担当者の連絡先も受け取っています。'),
('biz_sales_handoff', 1, 2, 'user39', 7, '初回説明会の人数と質問窓口も必要です。'),
('biz_sales_handoff', 1, 3, 'user25', 12, '参加は12名で、質問は管理担当者経由と聞いています。'),
('biz_sales_handoff', 1, 4, 'user08', 18, '導入計画に反映し、接続確認を前日に入れます。'),
('biz_sales_handoff', 1, 5, 'user39', 25, '説明会の案内文と準備物をまとめました'),
('biz_sales_handoff', 1, 6, 'user25', 33, '未確定項目がなくなったので、正式に引き継ぎます'),
('biz_sales_handoff', 1, 7, 'user08', 42, '引き継ぎ内容を受け取りました。開始後に連絡先が分散しないよう窓口を先方へ案内し、初回説明会の後に不足がなかったか共有します。'),

-- Customer success
('biz_cs_onboarding', 1, 1, 'user39', 3, '招待後に参加するチャンネルを選ぶところで迷っています。'),
('biz_cs_onboarding', 1, 2, 'user24', 7, '最初に必要な三つを固定して案内するとよさそうです。'),
('biz_cs_onboarding', 1, 3, 'user08', 12, '手順書の冒頭に推奨チャンネルを追加します。'),
('biz_cs_onboarding', 1, 4, 'user39', 18, '説明の順番も変え、開始までの時間を測りたいです。'),
('biz_cs_onboarding', 1, 5, 'user24', 25, '迷いやすい画面だけ画像例を添えましょう'),
('biz_cs_onboarding', 1, 6, 'user08', 33, '改善前後を同じ記録表で比較できるようにします'),
('biz_cs_onboarding', 1, 7, 'user39', 42, '次回は新しい順序で案内し、迷った場面をその場で記録します。改善しなかった場合も結果を隠さず、導線側の変更を相談しましょう。'),

('biz_cs_slow_response', 1, 1, 'user37', 3, '半年分の一覧を複数条件で絞ると再現します。'),
('biz_cs_slow_response', 1, 2, 'user06', 7, '初回表示は四秒ほどで、二回目は一秒以内でした。'),
('biz_cs_slow_response', 1, 3, 'user18', 12, '利用者には期間を短くする回避策を先に案内します。'),
('biz_cs_slow_response', 1, 4, 'user37', 18, '初回だけ走る取得処理を切り分けています。'),
('biz_cs_slow_response', 1, 5, 'user06', 25, '計測記録に条件と件数を加えておきました'),
('biz_cs_slow_response', 1, 6, 'user18', 33, '問い合わせには調査中と次回連絡日を伝えました'),
('biz_cs_slow_response', 1, 7, 'user37', 42, '再現条件と利用者への回避策を分けて整理しました。確認会では計測値を一緒に見て、ほかの課題との優先度を決めたいです。'),

('biz_cs_usage_review', 1, 1, 'user12', 3, '利用者数は増えましたが、共有機能は横ばいです。'),
('biz_cs_usage_review', 1, 2, 'user40', 7, '共有先の選択で迷うという問い合わせが二件ありました。'),
('biz_cs_usage_review', 1, 3, 'user29', 12, '次回説明会で短い操作例を見せましょう。'),
('biz_cs_usage_review', 1, 4, 'user12', 18, '効果は共有を実行した人数で追うのがよさそうです。'),
('biz_cs_usage_review', 1, 5, 'user40', 25, '問い合わせも操作前後で分類して比較します'),
('biz_cs_usage_review', 1, 6, 'user29', 33, '実演用のデータを用意し、所要時間も測ります'),
('biz_cs_usage_review', 1, 7, 'user12', 42, '共有実行人数だけで判断せず、操作中に迷った声も次月のレビューへ持ち寄りましょう。数字が変わらない場合も改善の手掛かりになります。'),

('biz_cs_feedback_route', 1, 1, 'user05', 3, '優先度を判断しやすいよう、受付時には影響人数と回避策の有無を必須にしたいです。'),
('biz_cs_feedback_route', 1, 2, 'user33', 7, '再現手順もあると開発側で判断しやすくなります。'),
('biz_cs_feedback_route', 1, 3, 'user22', 12, '三項目を受付票へ追加し、入力例も付けます。'),
('biz_cs_feedback_route', 1, 4, 'user05', 18, '過去分は影響が大きい要望だけ補えば十分です。'),
('biz_cs_feedback_route', 1, 5, 'user33', 25, '受け渡し後の担当者も記録できる欄がほしいです'),
('biz_cs_feedback_route', 1, 6, 'user22', 33, '担当欄を加え、週二回確認する流れにしました'),
('biz_cs_feedback_route', 1, 7, 'user05', 42, 'まず二週間、受付側と開発側の両方で使ってみましょう。抜けだけでなく記入負担も振り返り、続けやすい項目へ調整します。'),

('biz_cs_renewal_risk', 1, 1, 'user29', 3, '担当変更後に定例確認が止まり、質問が残っていました。'),
('biz_cs_renewal_risk', 1, 2, 'user40', 7, '現在の設定と未解決事項を新担当者向けに整理しましょう。'),
('biz_cs_renewal_risk', 1, 3, 'user15', 12, '今後使いたい業務も聞き、支援内容を見直したいです。'),
('biz_cs_renewal_risk', 1, 4, 'user29', 18, '整理表を作り、先方との確認会を調整しています。'),
('biz_cs_renewal_risk', 1, 5, 'user40', 25, '確認会前に質問を送り、優先順位を付けてもらいます'),
('biz_cs_renewal_risk', 1, 6, 'user15', 33, '更新の話だけでなく、利用再開の支援を中心に進めます'),
('biz_cs_renewal_risk', 1, 7, 'user29', 42, '確認会の日程候補を受け取りました。事前回答を三人で読み、先方が話したい課題から始められるよう進行を組みます。'),

-- Design
('biz_design_empty_state', 1, 1, 'user11', 3, '原因説明より、次にできる操作を先に出したいです。'),
('biz_design_empty_state', 1, 2, 'user31', 7, '条件を減らす操作と全解除の二案を作りました。'),
('biz_design_empty_state', 1, 3, 'user05', 12, '主要な操作が二つ並ぶと迷うかもしれません。'),
('biz_design_empty_state', 1, 4, 'user11', 18, '条件を減らす方をボタン、全解除を文中リンクにします。'),
('biz_design_empty_state', 1, 5, 'user31', 25, '修正版では視線の順序も自然になりました'),
('biz_design_empty_state', 1, 6, 'user05', 33, '検索条件が残ることも短く説明してください'),
('biz_design_empty_state', 1, 7, 'user11', 42, '説明を加えました。この案で利用確認へ進めます。'),

('biz_design_form_labels', 1, 1, 'user32', 3, '必須の印だけでは、任意か判断しにくいようです。'),
('biz_design_form_labels', 1, 2, 'user11', 7, '各項目へ必須または任意と文字で示しましょう。'),
('biz_design_form_labels', 1, 3, 'user18', 12, '画面読み上げでも同じ状態が伝わる必要があります。'),
('biz_design_form_labels', 1, 4, 'user32', 18, '長い項目名でも収まる配置で試作しました。'),
('biz_design_form_labels', 1, 5, 'user11', 25, '見た目でも読み上げでも区別できています。'),
('biz_design_form_labels', 1, 6, 'user18', 33, '入力途中の迷いが減るか利用確認で見ましょう'),
('biz_design_form_labels', 1, 7, 'user32', 42, '共通部品へ反映できるよう仕様をまとめます'),

('biz_design_dashboard_density', 1, 1, 'user38', 3, '毎日見る三指標だけを上段へまとめる案です。'),
('biz_design_dashboard_density', 1, 2, 'user16', 7, '担当者は未処理件数を最初に確認します。'),
('biz_design_dashboard_density', 1, 3, 'user27', 12, 'では未処理件数を左端に置いてください。'),
('biz_design_dashboard_density', 1, 4, 'user38', 18, '補助情報は比較しやすい表へ移しました。'),
('biz_design_dashboard_density', 1, 5, 'user16', 25, '色は異常な数値だけに使うと見つけやすいです。'),
('biz_design_dashboard_density', 1, 6, 'user27', 33, '情報量を保ったまま、優先順位が明確になりました'),
('biz_design_dashboard_density', 1, 7, 'user38', 42, '余白を整えて次の確認会へ出します'),

('biz_design_confirmation', 1, 1, 'user05', 3, '誤操作防止のため、対象名は表示したいです。'),
('biz_design_confirmation', 1, 2, 'user18', 7, '影響件数も分かると判断しやすくなります。'),
('biz_design_confirmation', 1, 3, 'user31', 12, '件数取得に時間がかかる場合の状態も用意します。'),
('biz_design_confirmation', 1, 4, 'user05', 18, '取得中は削除できない理由を説明してください。'),
('biz_design_confirmation', 1, 5, 'user18', 25, '取得失敗時には再試行できることも必要です。'),
('biz_design_confirmation', 1, 6, 'user31', 33, '待機、失敗、取得完了の三状態を作りました'),
('biz_design_confirmation', 1, 7, 'user05', 42, '対象と影響が確認できるので、この構成で進めます'),

('biz_design_mobile_navigation', 1, 1, 'user27', 3, '設定を個人メニューへ移して四項目にした案ですね。'),
('biz_design_mobile_navigation', 1, 2, 'user16', 7, '通知は利用頻度が高いため、下部に残してほしいです。'),
('biz_design_mobile_navigation', 1, 3, 'user38', 12, '通知を残し、履歴を一覧画面の中へ移します。'),
('biz_design_mobile_navigation', 1, 4, 'user27', 18, '組み替え後は、四つの主要操作へ片手で無理なく届きます。'),
('biz_design_mobile_navigation', 1, 5, 'user16', 25, '選択中の項目がもう少し明確だと助かります。'),
('biz_design_mobile_navigation', 1, 6, 'user38', 33, '文字と背景の両方で選択状態を示しました'),
('biz_design_mobile_navigation', 1, 7, 'user27', 42, '操作確認では項目の見つけやすさを測りましょう'),

-- Weekly reports
('biz_weekly_engineering', 1, 1, 'user06', 3, '検索改善は完了し、認証改善は設計確認まで進みました。'),
('biz_weekly_engineering', 1, 2, 'user23', 7, '画面側は予定どおりで、来週は異常系へ進みます。'),
('biz_weekly_engineering', 1, 3, 'user02', 12, '認証側を待つ項目だけ依存として明記してください。'),
('biz_weekly_engineering', 1, 4, 'user06', 18, '課題欄へ追記しましたが、日程への影響はありません。'),
('biz_weekly_engineering', 1, 5, 'user23', 25, '来週前半は待たずに進められる表示から着手します。'),
('biz_weekly_engineering', 1, 6, 'user02', 33, '完了、次週予定、課題の三点が揃いました'),
('biz_weekly_engineering', 1, 7, 'user06', 42, 'この内容を全体向けの週報へ反映します'),

('biz_weekly_support', 1, 1, 'user24', 3, '招待手順が四件、権限設定が三件ありました。'),
('biz_weekly_support', 1, 2, 'user39', 7, 'どちらも初回利用時で、案内導線に課題があります。'),
('biz_weekly_support', 1, 3, 'user08', 12, '招待完了画面から手順へ進める変更を試しましょう。'),
('biz_weekly_support', 1, 4, 'user24', 18, '回答用の短い手順も同じ内容へ更新します。'),
('biz_weekly_support', 1, 5, 'user39', 25, '改善前後で解決時間を記録すると比較できます'),
('biz_weekly_support', 1, 6, 'user08', 33, '件数と対応時間の両方を来週の確認対象にします'),
('biz_weekly_support', 1, 7, 'user24', 42, '記録欄を追加しました。次の問い合わせから使います。'),

('biz_weekly_business', 1, 1, 'user20', 3, '試用中の二社が継続検討へ進みました。'),
('biz_weekly_business', 1, 2, 'user30', 7, '要件確認待ちの一社は安全管理の回答待ちです。'),
('biz_weekly_business', 1, 3, 'user04', 12, '回答予定日も入れて、停滞理由を明確にしましょう。'),
('biz_weekly_business', 1, 4, 'user20', 18, '来週は試用後の評価面談が二件あります。'),
('biz_weekly_business', 1, 5, 'user30', 25, '面談前に利用状況を整理して担当へ渡します。'),
('biz_weekly_business', 1, 6, 'user04', 33, '案件数だけでなく、次の行動まで報告できています'),
('biz_weekly_business', 1, 7, 'user20', 42, '予定日と担当者を追記して週報を確定しました'),

('biz_weekly_risk', 1, 1, 'user37', 3, '外部連携の試験日が未確定な点を最優先にします。'),
('biz_weekly_risk', 1, 2, 'user13', 7, '一週間遅れると受け入れ期間が二日短くなります。'),
('biz_weekly_risk', 1, 3, 'user19', 12, '影響と判断期限を週報へ明記しましょう。'),
('biz_weekly_risk', 1, 4, 'user37', 18, '模擬環境で先に確認できる項目を分けました。'),
('biz_weekly_risk', 1, 5, 'user13', 25, '先行確認で短縮できる日数も見積もります。'),
('biz_weekly_risk', 1, 6, 'user19', 33, '判断期限は火曜午前として担当者を設定します'),
('biz_weekly_risk', 1, 7, 'user37', 42, '回避策と再確認時刻を報告へ反映しました'),

-- Procurement
('biz_procurement_laptops', 1, 1, 'user34', 3, '新規参加者用四台と故障交換用一台で、合計五台です。'),
('biz_procurement_laptops', 1, 2, 'user09', 7, '同じ構成なら保守手続きもまとめられます。'),
('biz_procurement_laptops', 1, 3, 'user21', 12, '在庫構成で開発要件を満たすか確認してください。'),
('biz_procurement_laptops', 1, 4, 'user34', 18, '在庫品なら一週間、構成変更では三週間かかります。'),
('biz_procurement_laptops', 1, 5, 'user09', 25, '在庫構成でも必要な性能と保証期間を満たしています。'),
('biz_procurement_laptops', 1, 6, 'user21', 33, 'では納期を優先し、在庫構成で申請します'),
('biz_procurement_laptops', 1, 7, 'user34', 42, '五台分の見積もりと納期回答を添付しました'),

('biz_procurement_room', 1, 1, 'user25', 3, '外部画面二台、電源タップ六本、接続器が必要です。'),
('biz_procurement_room', 1, 2, 'user17', 7, '会場側で画面一台と電源タップ四本を用意できます。'),
('biz_procurement_room', 1, 3, 'user40', 12, '不足分だけ持ち込む一覧に更新します。'),
('biz_procurement_room', 1, 4, 'user25', 18, '接続器は二種類必要なので、端子を記載しました。'),
('biz_procurement_room', 1, 5, 'user17', 25, '会場には一時間前から入室できます。'),
('biz_procurement_room', 1, 6, 'user40', 33, '前日の動作確認と当日の担当者を決めました'),
('biz_procurement_room', 1, 7, 'user25', 42, '不足品の手配も完了し、準備物が揃いました'),

('biz_procurement_subscription', 1, 1, 'user13', 3, '契約枠の八割を三チームが毎週利用しています。'),
('biz_procurement_subscription', 1, 2, 'user35', 7, '未使用の追加機能を外せば費用を抑えられます。'),
('biz_procurement_subscription', 1, 3, 'user26', 12, '標準機能だけで現在の運用を続けられますか。'),
('biz_procurement_subscription', 1, 4, 'user13', 18, '利用担当へ確認し、影響がないことが分かりました。'),
('biz_procurement_subscription', 1, 5, 'user35', 25, '標準機能だけの見積もりを取得します。'),
('biz_procurement_subscription', 1, 6, 'user26', 33, '申請理由に利用頻度と削減内容を記載します'),
('biz_procurement_subscription', 1, 7, 'user35', 42, '新しい見積もりが届き、前年より削減できました'),

('biz_procurement_delivery', 1, 1, 'user21', 3, '数量と外観は私が確認し、技術確認は担当へ依頼します。'),
('biz_procurement_delivery', 1, 2, 'user34', 7, '到着は午後予定なので、午前中に保管場所を空けます。'),
('biz_procurement_delivery', 1, 3, 'user17', 12, '数量と型番を迷わず照合できるよう、注文内容を並べた検品表を用意しました。'),
('biz_procurement_delivery', 1, 4, 'user21', 18, '不足時は管理番号と状態を記録しましょう。'),
('biz_procurement_delivery', 1, 5, 'user34', 25, '受け取り場所と連絡先を配送担当へ伝えました。'),
('biz_procurement_delivery', 1, 6, 'user17', 33, '技術確認の担当者も午後に対応できます'),
('biz_procurement_delivery', 1, 7, 'user21', 42, '役割が決まったので、到着後は一覧へ結果を残します'),

-- Announcements
('biz_announce_maintenance', 1, 1, 'user19', 3, '水曜19時から20時で、停止見込みは最大10分です。'),
('biz_announce_maintenance', 1, 2, 'user22', 7, '作業時間と接続できない時間を分けて書きます。'),
('biz_announce_maintenance', 1, 3, 'user01', 12, '影響する機能と、作業後の確認時刻も必要です。'),
('biz_announce_maintenance', 1, 4, 'user19', 18, '対象機能を二点に整理し、確認時刻を追記しました。'),
('biz_announce_maintenance', 1, 5, 'user22', 25, '問題が続く場合の次回案内時刻も入れています。'),
('biz_announce_maintenance', 1, 6, 'user01', 33, '利用者が予定を立てられる内容になりました'),
('biz_announce_maintenance', 1, 7, 'user22', 42, '案内を予約し、前日にも短い再案内を出します'),

('biz_announce_training', 1, 1, 'user40', 3, '対象者と開催時間に加え、当日までに用意するものも案内へ入れています。'),
('biz_announce_training', 1, 2, 'user28', 7, '欠席者向けの資料と録画の扱いも知りたいです。'),
('biz_announce_training', 1, 3, 'user11', 12, '録画はせず、説明資料だけ後日共有します。'),
('biz_announce_training', 1, 4, 'user40', 18, '申込締切と定員を追加しました。'),
('biz_announce_training', 1, 5, 'user28', 25, '質問先も案内の末尾にあると安心です'),
('biz_announce_training', 1, 6, 'user11', 33, '担当窓口を追記し、申込条件も明確にしました'),
('biz_announce_training', 1, 7, 'user40', 42, '内容を確認しました。この文面で公開します。'),

('biz_announce_policy', 1, 1, 'user10', 3, '新ルールは月初提出分から適用し、それ以前に提出した申請は旧ルールで扱います。'),
('biz_announce_policy', 1, 2, 'user29', 7, '申請途中の案件がどちらになるか例を入れてください。'),
('biz_announce_policy', 1, 3, 'user03', 12, '保存日ではなく提出日で判断する説明が必要ですね。'),
('biz_announce_policy', 1, 4, 'user10', 18, '月末保存、月初提出の例を追加しました。'),
('biz_announce_policy', 1, 5, 'user29', 25, '旧手順をいつまで見られるかも案内しましょう。'),
('biz_announce_policy', 1, 6, 'user03', 33, '掲載終了日があれば移行期間も分かりやすいです'),
('biz_announce_policy', 1, 7, 'user10', 42, '終了日を追記し、公開予約まで完了しました'),

('biz_announce_office', 1, 1, 'user34', 3, '対象階の利用者と当日の来訪予定者へ案内します。'),
('biz_announce_office', 1, 2, 'user40', 7, '点検中は一部の電源が停止しますが、会議室は使えます。'),
('biz_announce_office', 1, 3, 'user17', 12, '停止範囲は部屋番号で明記しましょう。'),
('biz_announce_office', 1, 4, 'user34', 18, '代替の作業場所も確保できています。'),
('biz_announce_office', 1, 5, 'user40', 25, '必要な方が連絡できる総務窓口を追記します。'),
('biz_announce_office', 1, 6, 'user17', 33, '対象者と影響範囲が明確になりました'),
('biz_announce_office', 1, 7, 'user34', 42, '本日中に案内し、前日に再度知らせます'),

-- FAQ
('biz_faq_password_reset', 1, 1, 'user15', 3, '今の回答は、再設定メールが見つからないときに何から確認するかが曖昧です。'),
('biz_faq_password_reset', 1, 2, 'user39', 7, '迷惑メール、登録先、再送間隔の順が分かりやすいです。'),
('biz_faq_password_reset', 1, 3, 'user24', 12, '連続して再送しない注意も入れましょう。'),
('biz_faq_password_reset', 1, 4, 'user15', 18, '三段階の確認と再送時の注意を追記しました。'),
('biz_faq_password_reset', 1, 5, 'user39', 25, '解決しない場合に伝える情報も案内したいです。'),
('biz_faq_password_reset', 1, 6, 'user24', 33, '端末、発生時刻、表示内容の三点に絞ります'),
('biz_faq_password_reset', 1, 7, 'user15', 42, '問い合わせまで迷わず進める回答になりました'),

('biz_faq_notifications', 1, 1, 'user29', 3, 'すべて切らず、個人宛てだけ残す例がよさそうです。'),
('biz_faq_notifications', 1, 2, 'user12', 7, 'パソコンと携帯で設定箇所が違う点に注意が必要です。'),
('biz_faq_notifications', 1, 3, 'user07', 12, 'まず緊急連絡を受け取れる設定例を載せましょう。'),
('biz_faq_notifications', 1, 4, 'user29', 18, '目的別に三つの設定例を用意しました。'),
('biz_faq_notifications', 1, 5, 'user12', 25, '二つの画面を分け、初期値も記載しています。'),
('biz_faq_notifications', 1, 6, 'user07', 33, '通知を減らす結果が例ごとに分かると親切です'),
('biz_faq_notifications', 1, 7, 'user29', 42, '受け取る通知の違いを各例へ追記しました'),

('biz_faq_channel_search', 1, 1, 'user18', 3, '最初はチャンネルで絞る例、次に投稿者で絞る例を分けて紹介しましょう。'),
('biz_faq_channel_search', 1, 2, 'user05', 7, '日付で絞る例も長期利用者には役立ちます。'),
('biz_faq_channel_search', 1, 3, 'user32', 12, '最後に三条件を組み合わせた例を追加します。'),
('biz_faq_channel_search', 1, 4, 'user18', 18, '検索語を置き換えやすい短い例にしてください。'),
('biz_faq_channel_search', 1, 5, 'user05', 25, '例を実際の画面で試し、同じ結果になりました。'),
('biz_faq_channel_search', 1, 6, 'user32', 33, '条件ごとの役割も一文ずつ説明しました'),
('biz_faq_channel_search', 1, 7, 'user18', 42, '基本から組み合わせまで自然に読める回答です'),

-- Secondary threads on later root posts
('biz_aurora_release_scope', 4, 1, 'user07', 2, '通知設定の確認だけを未完了として残す認識です。'),
('biz_aurora_release_scope', 4, 2, 'user14', 6, '検索側は試験まで終えているので、完了扱いで問題なさそうです。'),
('biz_aurora_release_scope', 4, 3, 'user07', 11, '確認結果を進行表と案内文の両方へ反映します'),
('biz_aurora_release_scope', 4, 4, 'user14', 17, '判定会までに状態が一目で分かるようになりました'),

('biz_aurora_data_migration', 3, 1, 'user22', 2, '補正対象は12件で、すべて管理番号を持っています。'),
('biz_aurora_data_migration', 3, 2, 'user14', 6, '補正前の値は一覧へ載せず、理由だけ残してください。'),
('biz_aurora_data_migration', 3, 3, 'user22', 11, '管理番号、補正理由、確認状態の三列にしました'),
('biz_aurora_data_migration', 3, 4, 'user14', 17, 'その形式なら確認用として共有できます'),

('biz_aurora_mobile_check', 4, 1, 'user32', 2, '主要な三サイズへ同じ最大幅を適用しました。'),
('biz_aurora_mobile_check', 4, 2, 'user05', 6, '横向きで操作ボタンが離れすぎないかも見たいです。'),
('biz_aurora_mobile_check', 4, 3, 'user32', 11, '余白を一段狭めても文字との重なりはありません'),
('biz_aurora_mobile_check', 4, 4, 'user05', 17, '操作しやすさも保てているので、この値で確定します'),

('biz_phoenix_sprint_plan', 4, 1, 'user23', 2, '通常系の文言はこの案で実装へ入れます。'),
('biz_phoenix_sprint_plan', 4, 2, 'user15', 6, '異常系の応答例は明日の午前中に揃えます。'),
('biz_phoenix_sprint_plan', 4, 3, 'user23', 11, '待ち時間は通常系の画面調整へ充てます'),
('biz_phoenix_sprint_plan', 4, 4, 'user15', 17, '依存を分けたので、着手の空白は発生しません'),

('biz_phoenix_accessibility', 3, 1, 'user31', 2, '同じ共通部品を使う画面を四つ確認しました。'),
('biz_phoenix_accessibility', 3, 2, 'user11', 6, '画面読み上げの確認対象もその四つで合っています。'),
('biz_phoenix_accessibility', 3, 3, 'user31', 11, '操作元へ戻ることと読み上げ順を試験へ追加します'),
('biz_phoenix_accessibility', 3, 4, 'user11', 17, '確認範囲が揃ったので、修正後にまとめて見ます'),

('biz_phoenix_api_contract', 4, 1, 'user33', 2, '省略された応答を試験データへ追加しました。'),
('biz_phoenix_api_contract', 4, 2, 'user28', 6, '画面では未設定表示へ置き換える実装にしています。'),
('biz_phoenix_api_contract', 4, 3, 'user33', 11, '値ありと省略の両方を自動試験へ入れます'),
('biz_phoenix_api_contract', 4, 4, 'user28', 17, '表示差分が確認できれば画面側は完了です'),

('biz_sales_discovery', 3, 1, 'user04', 2, '聞き取り前に機能を見せすぎないようにしましょう。'),
('biz_sales_discovery', 3, 2, 'user20', 6, '現行の承認手順を図にしながら聞く予定です。'),
('biz_sales_discovery', 3, 3, 'user04', 11, '課題が一致した部分だけ通知の例を見せます'),
('biz_sales_discovery', 3, 4, 'user20', 17, 'その流れなら先方の説明時間も十分に取れます'),

('biz_sales_proposal_revision', 4, 1, 'user10', 2, '回収時期が延びた理由を注記へ入れてください。'),
('biz_sales_proposal_revision', 4, 2, 'user16', 6, '先方が数字を追いやすいよう、習熟期間を見込んだ結果だと分かる表現にします。'),
('biz_sales_proposal_revision', 4, 3, 'user10', 11, '控えめな前提でも効果が残る点は説明できます'),
('biz_sales_proposal_revision', 4, 4, 'user16', 17, '注記とグラフの期間表示を同じ条件へ揃えました'),

('biz_sales_security_answers', 3, 1, 'user36', 2, '削除申請の受付から完了確認までを回答へ含めます。'),
('biz_sales_security_answers', 3, 2, 'user13', 6, '標準期間と個別条件を混ぜない構成がよさそうです。'),
('biz_sales_security_answers', 3, 3, 'user36', 11, '最初に標準条件、その後に相談窓口を記載しました'),
('biz_sales_security_answers', 3, 4, 'user13', 17, '先方が次に確認すべき内容も明確になっています'),

('biz_cs_onboarding', 4, 1, 'user24', 2, '画像例はチャンネル選択の一枚だけで十分だと思います。'),
('biz_cs_onboarding', 4, 2, 'user39', 6, '説明中もその画面で止まる方が多かったです。'),
('biz_cs_onboarding', 4, 3, 'user24', 11, '推奨する三つを画像内でも目立たせます'),
('biz_cs_onboarding', 4, 4, 'user39', 17, '次回は画像を見る時間も含めて所要時間を測ります'),

('biz_cs_slow_response', 3, 1, 'user37', 2, '初回取得の記録を追加して、処理単位で比較します。'),
('biz_cs_slow_response', 3, 2, 'user18', 6, '問い合わせには四秒という計測値はまだ出さずにおきます。'),
('biz_cs_slow_response', 3, 3, 'user37', 11, '原因が確定するまでは回避策と次回連絡日だけ伝えます'),
('biz_cs_slow_response', 3, 4, 'user18', 17, '利用者向けの案内と調査記録を分けて更新しました'),

('biz_cs_usage_review', 4, 1, 'user29', 2, '実演後に一度共有してもらう時間を設けます。'),
('biz_cs_usage_review', 4, 2, 'user40', 6, '操作中に迷った箇所も問い合わせ分類へ残したいです。'),
('biz_cs_usage_review', 4, 3, 'user29', 11, '実行人数と迷った箇所を同じ回で記録します'),
('biz_cs_usage_review', 4, 4, 'user40', 17, '数字と理由の両方を次月に比較できそうです'),

('biz_design_empty_state', 3, 1, 'user05', 2, '操作に迷わせないため、主要ボタンは一つに絞る方向でどうでしょう。'),
('biz_design_empty_state', 3, 2, 'user11', 6, '条件を減らす操作を主要にする案へ直します。'),
('biz_design_empty_state', 3, 3, 'user05', 11, '全解除は補助リンクなら必要な方だけ選べます'),
('biz_design_empty_state', 3, 4, 'user11', 17, '二つの優先度が伝わる配置になりました'),

('biz_design_form_labels', 4, 1, 'user18', 2, '読み上げでは必須と任意の両方が正しく伝わります。'),
('biz_design_form_labels', 4, 2, 'user11', 6, '入力例がある項目でも表示が重ならないか見ます。'),
('biz_design_form_labels', 4, 3, 'user18', 11, '長い入力例を含めても配置は崩れませんでした'),
('biz_design_form_labels', 4, 4, 'user11', 17, '共通表記として採用できる状態です'),

('biz_design_dashboard_density', 3, 1, 'user38', 2, '未処理件数を左端にした配置へ変更しました。'),
('biz_design_dashboard_density', 3, 2, 'user27', 6, '次に異常値、最後に処理済み件数の順が自然です。'),
('biz_design_dashboard_density', 3, 3, 'user38', 11, 'その順序に揃え、通常時の色を抑えました'),
('biz_design_dashboard_density', 3, 4, 'user27', 17, '重要な状態だけ色が出るので見つけやすいです'),

('biz_weekly_engineering', 4, 1, 'user06', 2, '認証側を待つのは異常系の表示二項目です。'),
('biz_weekly_engineering', 4, 2, 'user23', 6, '待つ項目を別枠にして、着手可能な作業と分けました。'),
('biz_weekly_engineering', 4, 3, 'user06', 11, '応答例は来週前半に渡せる予定です'),
('biz_weekly_engineering', 4, 4, 'user23', 17, '依存の期限も入ったので、週報から追えます'),

('biz_weekly_support', 3, 1, 'user08', 2, '招待完了画面に案内へのリンクを置く案で進めます。'),
('biz_weekly_support', 3, 2, 'user24', 6, '回答用手順も同じ案内へつなぐ形にします。'),
('biz_weekly_support', 3, 3, 'user08', 11, '導線を揃えると更新箇所も一つにできます'),
('biz_weekly_support', 3, 4, 'user24', 17, '次の問い合わせで案内まで自然に到達できるか、対応しながら確認してみます'),

('biz_procurement_laptops', 3, 1, 'user21', 2, '在庫構成で開発用の処理性能は満たしています。'),
('biz_procurement_laptops', 3, 2, 'user34', 6, '保証は標準で三年、故障時の交換にも対応します。'),
('biz_procurement_laptops', 3, 3, 'user21', 11, '要件と保証が揃うなら、構成変更は不要です'),
('biz_procurement_laptops', 3, 4, 'user34', 17, '在庫五台を一週間の納期で仮押さえしました'),

('biz_announce_maintenance', 4, 1, 'user19', 2, '利用者への影響としては、ログインと新規投稿の二機能を案内すればよさそうです。'),
('biz_announce_maintenance', 4, 2, 'user22', 6, '閲覧済みの画面でも再接続が必要と追記します。'),
('biz_announce_maintenance', 4, 3, 'user19', 11, '作業後は20時15分までに確認結果を共有します'),
('biz_announce_maintenance', 4, 4, 'user22', 17, '利用者が確認する時刻まで分かる案内になりました'),

('biz_faq_notifications', 3, 1, 'user07', 2, '最初は個人宛てと緊急連絡を残す例にしましょう。'),
('biz_faq_notifications', 3, 2, 'user29', 6, '携帯では時間帯による通知停止も組み合わせられます。'),
('biz_faq_notifications', 3, 3, 'user07', 11, '完全停止より前に、その設定を案内へ入れたいです'),
('biz_faq_notifications', 3, 4, 'user29', 17, '目的別の違いが分かる表へ更新しました');

COMMIT;
