PRAGMA foreign_keys = ON;
BEGIN;

DELETE FROM channel_conversation_thread_replies
WHERE conversation_id LIKE 'social_%';

INSERT INTO channel_conversation_thread_replies(
    conversation_id, root_step_order, reply_order, username, offset_minutes, message
) VALUES
-- town-square
('social_town_lunch_map', 1, 1, 'user18', 2, '出店場所は正面入口を出て右側です。'),
('social_town_lunch_map', 1, 2, 'user27', 5, '豆のカレーは辛さ控えめでしょうか？'),
('social_town_lunch_map', 1, 3, 'user18', 9, '香りはありますが、辛さはかなり穏やかでした。'),
('social_town_lunch_map', 1, 4, 'user12', 14, 'ご飯の量を少なめにもできるそうです。'),
('social_town_lunch_map', 1, 5, 'user27', 20, 'それなら今日はカレーにしてみます。'),
('social_town_lunch_map', 1, 6, 'user12', 27, '混む前に私も向かいます。'),
('social_town_lunch_map', 1, 7, 'user18', 35, '売り切れ表示はまだ出ていませんでした。'),

('social_town_lost_umbrella', 1, 1, 'user31', 2, '傘立ての近くを確認してみます。'),
('social_town_lost_umbrella', 1, 2, 'user08', 5, '持ち手や目印の特徴はありますか？'),
('social_town_lost_umbrella', 1, 3, 'user31', 9, '木の持ち手の傘が一本ありました。'),
('social_town_lost_umbrella', 1, 4, 'user20', 14, '白い小さな印も付いています。'),
('social_town_lost_umbrella', 1, 5, 'user08', 20, '見つかってよかったです。'),
('social_town_lost_umbrella', 1, 6, 'user20', 27, '受付横なら取り違えも少なそうですね。'),
('social_town_lost_umbrella', 1, 7, 'user31', 35, '倒れないよう奥側へ入れておきました。'),

('social_town_music_poll', 1, 1, 'user06', 2, '午後は少し明るい曲がよさそうです。'),
('social_town_music_poll', 1, 2, 'user35', 5, '歌詞が少ないものだと作業しやすいです。'),
('social_town_music_poll', 1, 3, 'user14', 9, '音量は会話を妨げない程度が希望です。'),
('social_town_music_poll', 1, 4, 'user06', 14, '器楽曲なら条件に合いそうですね。'),
('social_town_music_poll', 1, 5, 'user35', 20, '最初の曲、落ち着いていて好きです。'),
('social_town_music_poll', 1, 6, 'user14', 27, '席を離れるとほとんど聞こえない音量です。'),
('social_town_music_poll', 1, 7, 'user06', 35, 'この設定なら午後も続けられそうです。'),

('social_town_snack_share', 1, 1, 'user24', 2, '塩味のお菓子はどの箱でしょうか？'),
('social_town_snack_share', 1, 2, 'user16', 5, '青い箱がせんべい、白い箱が甘い方です。'),
('social_town_snack_share', 1, 3, 'user30', 9, '原材料の表示が残っているのは助かります。'),
('social_town_snack_share', 1, 4, 'user24', 14, '辛くないなら一枚いただきます。'),
('social_town_snack_share', 1, 5, 'user16', 20, '甘い方は小さな焼き菓子でした。'),
('social_town_snack_share', 1, 6, 'user30', 27, '飲み物の横へ紙ナプキンも置きました。'),
('social_town_snack_share', 1, 7, 'user24', 35, '休憩にちょうどよい量でした。'),

('social_town_window_weather', 1, 1, 'user32', 2, 'いま細かい雨が降り始めました。'),
('social_town_window_weather', 1, 2, 'user05', 5, '窓際に置いた紙だけ移動します。'),
('social_town_window_weather', 1, 3, 'user18', 9, '風向きが変わると少し吹き込みそうです。'),
('social_town_window_weather', 1, 4, 'user32', 14, '西側の窓は閉めた方がよさそうです。'),
('social_town_window_weather', 1, 5, 'user05', 20, '窓を閉めて入口のマットを出しました。'),
('social_town_window_weather', 1, 6, 'user18', 27, '外出中の方にも傘の連絡をしておきます。'),
('social_town_window_weather', 1, 7, 'user32', 35, '雨脚は少し弱くなってきました。'),

-- break-room
('social_break_coffee_grind', 1, 1, 'user19', 2, '通話が終わったので、今なら大丈夫です。'),
('social_break_coffee_grind', 1, 2, 'user28', 5, '今日は深煎りの香りですね。'),
('social_break_coffee_grind', 1, 3, 'user11', 9, '音は廊下までは聞こえていません。'),
('social_break_coffee_grind', 1, 4, 'user19', 14, '一分くらいなら気にならないと思います。'),
('social_break_coffee_grind', 1, 5, 'user28', 20, 'お湯が余れば少し分けてください。'),
('social_break_coffee_grind', 1, 6, 'user11', 27, '小さいカップを棚から出しました。'),
('social_break_coffee_grind', 1, 7, 'user28', 35, '香りも味も落ち着いていておいしいです。'),

('social_break_fridge_label', 1, 1, 'user11', 2, '緑のふたなら私が昨日入れたものです。'),
('social_break_fridge_label', 1, 2, 'user33', 5, '同じ形の容器が多いので迷いますね。'),
('social_break_fridge_label', 1, 3, 'user06', 9, '付箋とペンを横に置くのはどうでしょう。'),
('social_break_fridge_label', 1, 4, 'user11', 14, '今日中に持ち帰る予定です。'),
('social_break_fridge_label', 1, 5, 'user33', 20, '油性ペンを一本補充しておきました。'),
('social_break_fridge_label', 1, 6, 'user06', 27, '日付も書くと整理しやすそうです。'),
('social_break_fridge_label', 1, 7, 'user11', 35, '名前と日付を書いた札を付けました。'),

('social_break_stretch', 1, 1, 'user07', 2, '椅子に座ったままの動きならすぐできます。'),
('social_break_stretch', 1, 2, 'user13', 5, '三分だけ参加してみたいです。'),
('social_break_stretch', 1, 3, 'user31', 9, '肩を上げるときは息を止めない方がよいですか？'),
('social_break_stretch', 1, 4, 'user07', 14, 'はい、ゆっくり呼吸しながら動かしましょう。'),
('social_break_stretch', 1, 5, 'user13', 20, '首の横が少し伸びる感じがします。'),
('social_break_stretch', 1, 6, 'user31', 27, '無理に回さないので安心ですね。'),
('social_break_stretch', 1, 7, 'user07', 35, '痛みが出る前に止めれば十分です。'),

('social_break_tea_choice', 1, 1, 'user17', 2, '朝なので、ほうじ茶を試したいです。'),
('social_break_tea_choice', 1, 2, 'user38', 5, '柑橘の紅茶は午後に合いそうですね。'),
('social_break_tea_choice', 1, 3, 'user09', 9, 'ほうじ茶は香りが穏やかでしょうか？'),
('social_break_tea_choice', 1, 4, 'user17', 14, '香ばしいですが、強すぎない香りです。'),
('social_break_tea_choice', 1, 5, 'user38', 20, '茶葉の量は缶に書いてありますか？'),
('social_break_tea_choice', 1, 6, 'user09', 27, 'ふたに一杯分の目安が貼ってあります。'),
('social_break_tea_choice', 1, 7, 'user17', 35, '仕事前にも飲みやすい味でした。'),

('social_break_fan_setting', 1, 1, 'user10', 2, '弱なら寒くないと思います。'),
('social_break_fan_setting', 1, 2, 'user21', 5, '壁へ向けると風が柔らかくなりそうです。'),
('social_break_fan_setting', 1, 3, 'user28', 9, '窓も少し開けておきますか？'),
('social_break_fan_setting', 1, 4, 'user10', 14, '外の音が入らない程度ならよさそうです。'),
('social_break_fan_setting', 1, 5, 'user21', 20, '空気が少し動いて快適になりました。'),
('social_break_fan_setting', 1, 6, 'user28', 27, '最後に出るとき窓を閉めます。'),
('social_break_fan_setting', 1, 7, 'user10', 35, 'この向きなら直接風が当たりません。'),

-- late-night-talk
('social_late_release_pause', 1, 1, 'user15', 2, '主要な動作確認までは終わりました。'),
('social_late_release_pause', 1, 2, 'user26', 5, '残りは急ぎでなければ明日に回しましょう。'),
('social_late_release_pause', 1, 3, 'user07', 9, '今夜の差分は小さくまとまっていますか？'),
('social_late_release_pause', 1, 4, 'user15', 14, '表示調整が一件だけ残っています。'),
('social_late_release_pause', 1, 5, 'user26', 20, '明るい時間に画面を見直す方が安心です。'),
('social_late_release_pause', 1, 6, 'user07', 27, '確認項目を三つに整理しておきました。'),
('social_late_release_pause', 1, 7, 'user15', 35, '保存できたので、今日はここで止めます。'),

('social_late_rain_sound', 1, 1, 'user08', 2, 'あと十分で区切る予定です。'),
('social_late_rain_sound', 1, 2, 'user40', 5, '入口に共有の大きな傘があります。'),
('social_late_rain_sound', 1, 3, 'user23', 9, '雨雲はしばらく残りそうですね。'),
('social_late_rain_sound', 1, 4, 'user08', 14, '作業内容を保存して、TODOも残しました。'),
('social_late_rain_sound', 1, 5, 'user40', 20, '足元が暗いので帰り道は気を付けてください。'),
('social_late_rain_sound', 1, 6, 'user23', 27, '強くなる前に私も切り上げます。'),
('social_late_rain_sound', 1, 7, 'user08', 35, '傘を借りて帰ります。情報助かりました。'),

('social_late_bookmark', 1, 1, 'user29', 2, '今夜読むものだけ先に分けるとよさそうです。'),
('social_late_bookmark', 1, 2, 'user05', 5, '題名に一行メモを添えるだけでも十分です。'),
('social_late_bookmark', 1, 3, 'user12', 9, '結論に直接関係するページは何件ありますか？'),
('social_late_bookmark', 1, 4, 'user29', 14, '三件なら、今夜はそこまでに絞れそうですね。'),
('social_late_bookmark', 1, 5, 'user05', 20, '残りは明日読む箱へ移しましょう。'),
('social_late_bookmark', 1, 6, 'user12', 27, '分類名を短くすると後から探しやすいです。'),
('social_late_bookmark', 1, 7, 'user29', 35, '続きが分かる状態なら今日は十分です。'),

('social_late_keyboard', 1, 1, 'user37', 2, '静かな環境ほど打鍵音が気になりますね。'),
('social_late_keyboard', 1, 2, 'user01', 5, '無理せず一区切りで休んでください。'),
('social_late_keyboard', 1, 3, 'user14', 9, '環境音を小さく流すと和らぐかもしれません。'),
('social_late_keyboard', 1, 4, 'user37', 14, '雨音くらいなら集中を邪魔しにくいです。'),
('social_late_keyboard', 1, 5, 'user01', 20, 'タイマーも付けておくと安心ですね。'),
('social_late_keyboard', 1, 6, 'user14', 27, '明日の最初の作業だけメモして終えましょう。'),
('social_late_keyboard', 1, 7, 'user37', 35, '保存を確認したら画面を閉じるのがよさそうです。'),

-- remote-lounge
('social_remote_mic_test', 1, 1, 'user24', 2, '声は聞こえますが、机の音も少し入っています。'),
('social_remote_mic_test', 1, 2, 'user39', 5, 'マイクの下に布を敷くと改善するかもしれません。'),
('social_remote_mic_test', 1, 3, 'user10', 9, '自動音量調整も一度確認してみてください。'),
('social_remote_mic_test', 1, 4, 'user24', 14, 'いまは振動音がかなり減りました。'),
('social_remote_mic_test', 1, 5, 'user39', 20, '声の大きさはそのままで大丈夫です。'),
('social_remote_mic_test', 1, 6, 'user10', 27, '息の音も強く入っていません。'),
('social_remote_mic_test', 1, 7, 'user24', 35, 'この設定なら朝の通話で使えそうです。'),

('social_remote_delivery', 1, 1, 'user03', 2, '急ぎの確認はこちらで先に拾います。'),
('social_remote_delivery', 1, 2, 'user30', 5, '共有メモに優先順を付けておきます。'),
('social_remote_delivery', 1, 3, 'user20', 9, '応答が必要なものは今のところ一件です。'),
('social_remote_delivery', 1, 4, 'user03', 14, 'その一件も十五時までで大丈夫でした。'),
('social_remote_delivery', 1, 5, 'user30', 20, '戻ったときに上から見れば追える状態です。'),
('social_remote_delivery', 1, 6, 'user20', 27, '不在中の経緯も短く残しておきます。'),
('social_remote_delivery', 1, 7, 'user03', 35, 'こちらは落ち着いているので慌てなくて大丈夫です。'),

('social_remote_sunlight', 1, 1, 'user28', 2, '窓に対して横向きだと映り込みが減ります。'),
('social_remote_sunlight', 1, 2, 'user40', 5, '薄い布を一枚掛ける方法もあります。'),
('social_remote_sunlight', 1, 3, 'user04', 9, '机を動かすなら通路幅だけ確認してください。'),
('social_remote_sunlight', 1, 4, 'user28', 14, '少し回すだけでも違いが出ると思います。'),
('social_remote_sunlight', 1, 5, 'user40', 20, '午後は暗くなるので戻しやすい配置がよさそうです。'),
('social_remote_sunlight', 1, 6, 'user04', 27, '電源ケーブルにも余裕を持たせてください。'),
('social_remote_sunlight', 1, 7, 'user28', 35, '画面の明るさを上げすぎずに済みそうですね。'),

('social_remote_focus_block', 1, 1, 'user09', 2, '急ぎの連絡はこちらで拾っておきます。'),
('social_remote_focus_block', 1, 2, 'user17', 5, '私も同じ時間を集中枠にします。'),
('social_remote_focus_block', 1, 3, 'user22', 9, '終了予定が分かるので連絡を待ちやすいです。'),
('social_remote_focus_block', 1, 4, 'user09', 14, '割り込みが必要なら明記しておきます。'),
('social_remote_focus_block', 1, 5, 'user17', 20, '通知を一時間だけ静かにしました。'),
('social_remote_focus_block', 1, 6, 'user22', 27, 'こちらの確認は戻ってからで大丈夫です。'),
('social_remote_focus_block', 1, 7, 'user09', 35, '今のところ急ぎの連絡はありません。'),

-- office-events
('social_event_boardgame', 1, 1, 'user21', 2, '三十分で終わるものなら参加しやすいです。'),
('social_event_boardgame', 1, 2, 'user34', 5, '四人用と六人用を一つずつ持参できます。'),
('social_event_boardgame', 1, 3, 'user15', 9, '途中から見学だけでも大丈夫でしょうか？'),
('social_event_boardgame', 1, 4, 'user21', 14, '自由参加なら予定を合わせやすいですね。'),
('social_event_boardgame', 1, 5, 'user34', 20, '最初は説明が短い方を出します。'),
('social_event_boardgame', 1, 6, 'user15', 27, '十七時ごろに少し覗いてみます。'),
('social_event_boardgame', 1, 7, 'user21', 35, '人数が多ければ二卓に分かれましょう。'),

('social_event_photo_walk', 1, 1, 'user26', 2, 'スマートフォンだけでも参加できますか？'),
('social_event_photo_walk', 1, 2, 'user36', 5, '日陰の多い短い経路だとうれしいです。'),
('social_event_photo_walk', 1, 3, 'user08', 9, '建物の裏側に木陰が続く道があります。'),
('social_event_photo_walk', 1, 4, 'user26', 14, '道具を選ばないなら気軽に参加できますね。'),
('social_event_photo_walk', 1, 5, 'user36', 20, '十五分くらいなら昼休みに収まりそうです。'),
('social_event_photo_walk', 1, 6, 'user08', 27, '雨の場合は室内の光を探す会にできます。'),
('social_event_photo_walk', 1, 7, 'user26', 35, '当日の天気を見て入口へ行きます。'),

('social_event_lightning_talk', 1, 1, 'user04', 2, 'メモの整理方法なら五分で話せそうです。'),
('social_event_lightning_talk', 1, 2, 'user25', 5, '実際の画面が一枚あると伝わりやすいです。'),
('social_event_lightning_talk', 1, 3, 'user17', 9, '導入とまとめに一分ずつ使えそうですね。'),
('social_event_lightning_talk', 1, 4, 'user04', 14, '個人情報を消した例を準備します。'),
('social_event_lightning_talk', 1, 5, 'user25', 20, '残り一分で合図を出しましょうか？'),
('social_event_lightning_talk', 1, 6, 'user17', 27, '質疑は次の休憩で受ける形でもよさそうです。'),
('social_event_lightning_talk', 1, 7, 'user04', 35, '時間内に収まるよう一度練習します。'),

('social_event_cleanup', 1, 1, 'user10', 2, '机と椅子を戻す作業なら担当できます。'),
('social_event_cleanup', 1, 2, 'user38', 5, '飲み物とごみの確認を引き受けます。'),
('social_event_cleanup', 1, 3, 'user06', 9, '分別用の袋は会場にありますか？'),
('social_event_cleanup', 1, 4, 'user10', 14, '机の配置を写真に残しておくと戻しやすいです。'),
('social_event_cleanup', 1, 5, 'user38', 20, '袋は入口の箱に三種類あります。'),
('social_event_cleanup', 1, 6, 'user06', 27, '最後に忘れ物も一周確認します。'),
('social_event_cleanup', 1, 7, 'user10', 35, '三人いれば十分ほどで終わりそうです。'),

('social_event_breakfast', 1, 1, 'user33', 2, '八時半からなら参加できます。'),
('social_event_breakfast', 1, 2, 'user06', 5, 'パンと果物を少量ずつ用意できます。'),
('social_event_breakfast', 1, 3, 'user12', 9, '温かい飲み物があるとうれしいです。'),
('social_event_breakfast', 1, 4, 'user33', 14, '自由参加なら朝の予定に合わせやすいですね。'),
('social_event_breakfast', 1, 5, 'user06', 20, '食べ物の原材料も前日に書いておきます。'),
('social_event_breakfast', 1, 6, 'user12', 27, '飲み物はお茶とコーヒーがあれば十分です。'),
('social_event_breakfast', 1, 7, 'user33', 35, '少し早く着いた日に立ち寄ります。'),

-- onboarding
('social_onboard_channel_map', 1, 1, 'user02', 2, '最初は全体案内と担当に近い場所だけで十分です。'),
('social_onboard_channel_map', 1, 2, 'user14', 5, '雑談の過去ログは全部読まなくて大丈夫です。'),
('social_onboard_channel_map', 1, 3, 'user31', 9, '通知も少しずつ調整すると迷いにくいです。'),
('social_onboard_channel_map', 1, 4, 'user02', 14, '固定投稿にチャンネルの用途一覧があります。'),
('social_onboard_channel_map', 1, 5, 'user14', 20, '参加してから必要な場所を増やしていきましょう。'),
('social_onboard_channel_map', 1, 6, 'user31', 27, '分からない略語はここで質問できます。'),
('social_onboard_channel_map', 1, 7, 'user02', 35, 'まず二つ見られれば初日は十分です。'),

('social_onboard_profile', 1, 1, 'user12', 2, '担当と話しかけてよい話題が一つあれば十分です。'),
('social_onboard_profile', 1, 2, 'user27', 5, '呼んでほしい名前も書いてあると助かります。'),
('social_onboard_profile', 1, 3, 'user09', 9, '勤務時間の目安も任意で追加できます。'),
('social_onboard_profile', 1, 4, 'user12', 14, '長い経歴を書く必要はありません。'),
('social_onboard_profile', 1, 5, 'user27', 20, '好きな飲み物の話題は声をかけやすいですね。'),
('social_onboard_profile', 1, 6, 'user09', 27, '後から何度でも直せるので気軽に始めましょう。'),
('social_onboard_profile', 1, 7, 'user12', 35, '二、三行にまとまっていれば読みやすいです。'),

('social_onboard_first_meeting', 1, 1, 'user17', 2, '昨日と今日の予定を一行ずつで大丈夫です。'),
('social_onboard_first_meeting', 1, 2, 'user05', 5, '最初は聞いているだけでも問題ありません。'),
('social_onboard_first_meeting', 1, 3, 'user28', 9, '困りごとがなければ、特になしと伝えられます。'),
('social_onboard_first_meeting', 1, 4, 'user17', 14, '一人あたり一分ほどの短い会です。'),
('social_onboard_first_meeting', 1, 5, 'user05', 20, '事前に箇条書きを二つ作ると安心です。'),
('social_onboard_first_meeting', 1, 6, 'user28', 27, '順番が来るまではほかの人の共有を聞けます。'),
('social_onboard_first_meeting', 1, 7, 'user17', 35, '分からなければその場で聞いてください。'),

('social_onboard_terms', 1, 1, 'user09', 2, 'よく使う言葉の一覧が固定投稿にあります。'),
('social_onboard_terms', 1, 2, 'user35', 5, '一覧にない言葉はその場で聞いて大丈夫です。'),
('social_onboard_terms', 1, 3, 'user16', 9, '略語だけでなく正式な名前も書いてあります。'),
('social_onboard_terms', 1, 4, 'user09', 14, '検索すると過去の説明もいくつか見つかります。'),
('social_onboard_terms', 1, 5, 'user35', 20, '新しい言葉は回答後に一覧へ足しましょう。'),
('social_onboard_terms', 1, 6, 'user16', 27, '文脈によって意味が違う場合も補足できます。'),
('social_onboard_terms', 1, 7, 'user09', 35, '遠慮せず一つずつ確認するのが早いです。'),

('social_onboard_lunch_invite', 1, 1, 'user16', 2, '今日は数人で近くへ行く予定です。'),
('social_onboard_lunch_invite', 1, 2, 'user24', 5, '十二時十五分に入口へ集まります。'),
('social_onboard_lunch_invite', 1, 3, 'user03', 9, 'ゆっくり歩いて行ける距離の店です。'),
('social_onboard_lunch_invite', 1, 4, 'user16', 14, '注文に迷っても店頭で選べます。'),
('social_onboard_lunch_invite', 1, 5, 'user24', 20, '食べられないものがあれば先に教えてください。'),
('social_onboard_lunch_invite', 1, 6, 'user03', 27, '予定が変わった場合も気にしなくて大丈夫です。'),
('social_onboard_lunch_invite', 1, 7, 'user16', 35, '初日なので、分からないことも道中で聞けますよ。'),

-- weekend-club
('social_weekend_walk', 1, 1, 'user30', 2, '九時開始なら参加できます。'),
('social_weekend_walk', 1, 2, 'user13', 5, '橋の近くから途中参加したいです。'),
('social_weekend_walk', 1, 3, 'user21', 9, '速すぎないペースなら私も歩けそうです。'),
('social_weekend_walk', 1, 4, 'user30', 14, '三十分ほどで同じ場所へ戻りましょう。'),
('social_weekend_walk', 1, 5, 'user13', 20, '合流前にここへ連絡をもらえると助かります。'),
('social_weekend_walk', 1, 6, 'user21', 27, '水と帽子だけ持っていきます。'),
('social_weekend_walk', 1, 7, 'user30', 35, '雨なら無理せず次の週へ延期しましょう。'),

('social_weekend_cooking', 1, 1, 'user33', 2, '切るものが少ないレシピだとうれしいです。'),
('social_weekend_cooking', 1, 2, 'user04', 5, '塩だけでも味はまとまりますか？'),
('social_weekend_cooking', 1, 3, 'user18', 9, '冷凍野菜なら分量も調整しやすそうです。'),
('social_weekend_cooking', 1, 4, 'user33', 14, '豆の水煮は汁を切って使いますか？'),
('social_weekend_cooking', 1, 5, 'user04', 20, '香辛料は最後に少しだけ足すのがよさそうですね。'),
('social_weekend_cooking', 1, 6, 'user18', 27, '多めに作れば翌日の昼にも使えそうです。'),
('social_weekend_cooking', 1, 7, 'user33', 35, '材料がそろっているので週末に試します。'),

('social_weekend_puzzle', 1, 1, 'user36', 2, '十分ほどで解ける難しさがよさそうです。'),
('social_weekend_puzzle', 1, 2, 'user18', 5, '言葉遊びなら一問用意できます。'),
('social_weekend_puzzle', 1, 3, 'user11', 9, 'ヒントを二段階に分けると遊びやすそうです。'),
('social_weekend_puzzle', 1, 4, 'user36', 14, '初めての人もいるので競争にはしないでおきましょう。'),
('social_weekend_puzzle', 1, 5, 'user18', 20, '答えは別の紙にして封筒へ入れます。'),
('social_weekend_puzzle', 1, 6, 'user11', 27, '解けた人は次のヒント役になれますね。'),
('social_weekend_puzzle', 1, 7, 'user36', 35, '三問くらいあれば十分楽しめそうです。'),

('social_weekend_plants', 1, 1, 'user25', 2, '余っている土を少し持っていけます。'),
('social_weekend_plants', 1, 2, 'user14', 5, '鉢の底に敷く小石もあります。'),
('social_weekend_plants', 1, 3, 'user30', 9, '作業する場所へ新聞紙を持参します。'),
('social_weekend_plants', 1, 4, 'user25', 14, '十センチの鉢一つなら小袋で足ります。'),
('social_weekend_plants', 1, 5, 'user14', 20, '水は植え替え直後に少量でよさそうです。'),
('social_weekend_plants', 1, 6, 'user30', 27, '土がこぼれても片付けやすい準備にします。'),
('social_weekend_plants', 1, 7, 'user25', 35, '土と小石を別々の袋へ入れました。'),

-- one-liner
('social_one_pen', 1, 1, 'user32', 2, '芯の太さはどのくらいですか？'),
('social_one_pen', 1, 2, 'user22', 5, '細めで滑らかなものなら試したいです。'),
('social_one_pen', 1, 3, 'user06', 9, '紙の裏へ抜けにくいインクでしょうか？'),
('social_one_pen', 1, 4, 'user32', 14, '小さい文字もつぶれにくそうですね。'),
('social_one_pen', 1, 5, 'user22', 20, '予備を一本借りて書いてみます。'),
('social_one_pen', 1, 6, 'user06', 27, '乾きも早くて手に付きにくいです。'),
('social_one_pen', 1, 7, 'user22', 35, '次に買うときの候補にします。'),

('social_one_cloud', 1, 1, 'user01', 2, '私は大きな葉っぱにも見えます。'),
('social_one_cloud', 1, 2, 'user39', 5, '端の方が尾びれみたいですね。'),
('social_one_cloud', 1, 3, 'user14', 9, '少しずつ形が崩れてきました。'),
('social_one_cloud', 1, 4, 'user01', 14, '今度は羽を広げた鳥にも見えます。'),
('social_one_cloud', 1, 5, 'user39', 20, '青空が少し見えてきました。'),
('social_one_cloud', 1, 6, 'user14', 27, '数分で印象が変わるのが面白いです。'),
('social_one_cloud', 1, 7, 'user01', 35, '最後は細い線だけ残りました。'),

('social_one_timer', 1, 1, 'user35', 2, '休憩も時間を測っていますか？'),
('social_one_timer', 1, 2, 'user09', 5, '着手までが短くなるのはよいですね。'),
('social_one_timer', 1, 3, 'user24', 9, '二十五分なら試しやすそうです。'),
('social_one_timer', 1, 4, 'user35', 14, '五分休憩では席を立つようにします。'),
('social_one_timer', 1, 5, 'user09', 20, '最初は一回だけ試してみます。'),
('social_one_timer', 1, 6, 'user24', 27, '終了音が小さいものを選びたいです。'),
('social_one_timer', 1, 7, 'user09', 35, '一つ終わったので短い休憩に入ります。'),

('social_one_socks', 1, 1, 'user06', 2, '色が近ければ新しい組み合わせです。'),
('social_one_socks', 1, 2, 'user31', 5, 'よく見ないと気付かないかもしれません。'),
('social_one_socks', 1, 3, 'user18', 9, '片方だけ模様があるのも楽しそうです。'),
('social_one_socks', 1, 4, 'user06', 14, '朝から少し元気が出る話ですね。'),
('social_one_socks', 1, 5, 'user31', 20, '今日はそのまま堂々と過ごしましょう。'),
('social_one_socks', 1, 6, 'user18', 27, '帰宅したら相方が見つかるとよいですね。'),
('social_one_socks', 1, 7, 'user06', 35, '次は別の組み合わせも期待しています。'),

-- mystery-lab
('social_mystery_clock', 1, 1, 'user20', 2, '私の端末と比べても三分進んでいます。'),
('social_mystery_clock', 1, 2, 'user12', 5, '以前から少し進めていると聞いた気がします。'),
('social_mystery_clock', 1, 3, 'user27', 9, '電池が弱いなら遅れる方が自然ですね。'),
('social_mystery_clock', 1, 4, 'user20', 14, '時計の裏側に小さな表示があります。'),
('social_mystery_clock', 1, 5, 'user12', 20, '三分進み、と手書きで書かれています。'),
('social_mystery_clock', 1, 6, 'user27', 27, '遅刻防止のために設定したようですね。'),
('social_mystery_clock', 1, 7, 'user20', 35, '表側にも分かる表示があると親切です。'),

('social_mystery_footprints', 1, 1, 'user38', 2, '丸が二つ並んでいて足跡に見えます。'),
('social_mystery_footprints', 1, 2, 'user07', 5, '窓が閉まっているなら外からではなさそうです。'),
('social_mystery_footprints', 1, 3, 'user11', 9, '近くの植木鉢を動かした跡ではありませんか？'),
('social_mystery_footprints', 1, 4, 'user38', 14, '鉢の底に同じ形の突起があります。'),
('social_mystery_footprints', 1, 5, 'user07', 20, '水やりのときに付いた跡のようですね。'),
('social_mystery_footprints', 1, 6, 'user11', 27, '受け皿を置けば次から防げそうです。'),
('social_mystery_footprints', 1, 7, 'user38', 35, '謎が解けたので跡を拭いておきます。'),

('social_mystery_note', 1, 1, 'user23', 2, '数字は今日の日付と関係ありそうです。'),
('social_mystery_note', 1, 2, 'user34', 5, '裏面に薄い文字が残っています。'),
('social_mystery_note', 1, 3, 'user09', 9, '順番を入れ替えると日付になりますね。'),
('social_mystery_note', 1, 4, 'user23', 14, '昼の予定という文字も読めます。'),
('social_mystery_note', 1, 5, 'user34', 20, '昼食の受け取り番号かもしれません。'),
('social_mystery_note', 1, 6, 'user09', 27, '近くの人へ心当たりを聞いてみましょう。'),
('social_mystery_note', 1, 7, 'user23', 35, '持ち主が見つかるまで机の端へ置きます。'),

('social_mystery_hum', 1, 1, 'user11', 2, '危険な音というより機械の待機音に近いです。'),
('social_mystery_hum', 1, 2, 'user19', 5, '音と同時に光るランプはありますか？'),
('social_mystery_hum', 1, 3, 'user35', 9, '壁際の小さなランプが点滅しています。'),
('social_mystery_hum', 1, 4, 'user11', 14, '空気清浄機の表示かもしれません。'),
('social_mystery_hum', 1, 5, 'user19', 20, '説明にはフィルター確認とあります。'),
('social_mystery_hum', 1, 6, 'user35', 27, '交換時期を知らせる音だったようです。'),
('social_mystery_hum', 1, 7, 'user11', 35, '原因が分かったので担当へ連絡します。');

COMMIT;
