PRAGMA foreign_keys = ON;
BEGIN;

DELETE FROM channel_conversation_steps
WHERE conversation_id LIKE 'tech\_%' ESCAPE '\';

INSERT INTO channel_conversation_steps
    (conversation_id, step_order, channel_name, username, day_offset, minute_of_day, message)
VALUES
    ('tech_webhook_signature', 1, 'bot-dev-lab', 'user07', 1, 540, '@user02 Webhookの署名検証で不一致が続くため、受信ログと送信側の計算手順を突き合わせました。秘密鍵と時刻ヘッダーは一致していますが、JSONを整形した後だけ署名値が変わります。こちらでは改行を含む生の本文を保存できており、再現用のfixtureも用意しました。本文のどの段階でハッシュを計算しているか確認してもらえますか？ 条件が分かれば、生本文へ統一するか正規化規則を明示するかを判断したいです。'),
    ('tech_webhook_signature', 2, 'bot-dev-lab', 'user02', 1, 544, '確認します。本文をJSONへ整形し直した後のバイト列で署名を計算していました。'),
    ('tech_webhook_signature', 3, 'bot-dev-lab', 'user15', 1, 549, '受信した生の本文を使うように変えれば、改行や空白の差も含めて検証できます。'),
    ('tech_webhook_signature', 4, 'bot-dev-lab', 'user07', 1, 555, '生の本文へ切り替えたところ、正しい署名は通り、不正な署名は401になりました。'),
    ('tech_webhook_signature', 5, 'bot-dev-lab', 'user02', 1, 560, '時刻ヘッダーが古いリクエストも拒否できることを追加で確認します。'),
    ('tech_webhook_signature', 6, 'bot-dev-lab', 'user15', 1, 566, '許容時間を5分にして再送試験まで通りました。検証条件を手順書へ残します。'),

    ('tech_retry_backoff', 1, 'bot-dev-lab', 'user20', 4, 660, '@user28 APIが429を返した場合の再試行間隔を確認してもらえますか？'),
    ('tech_retry_backoff', 2, 'bot-dev-lab', 'user28', 4, 664, '現在は1秒固定なので、短時間に同じ失敗を繰り返しています。'),
    ('tech_retry_backoff', 3, 'bot-dev-lab', 'user33', 4, 669, '待機を1秒、2秒、4秒と延ばし、応答のRetry-Afterがあれば優先しましょう。'),
    ('tech_retry_backoff', 4, 'bot-dev-lab', 'user20', 4, 675, '@user33 最大待機を30秒に制限した実装を入れました。試験をお願いします。'),
    ('tech_retry_backoff', 5, 'bot-dev-lab', 'user33', 4, 681, '連続3回の429後に成功し、要求回数も想定内へ収まりました。'),
    ('tech_retry_backoff', 6, 'bot-dev-lab', 'user28', 4, 687, '間隔案が具体的で助かりました。再試行回数と最終エラーもログへ残したので、運用時の追跡項目はこれで足りそうでしょうか？'),

    ('tech_permission_scope', 1, 'bot-dev-lab', 'user15', 7, 840, '@user07 Botへ付与する権限が広すぎるようです。必要な操作を整理しましょう。'),
    ('tech_permission_scope', 2, 'bot-dev-lab', 'user07', 7, 845, '利用するのは投稿作成、リアクション追加、対象チャンネルの閲覧だけです。'),
    ('tech_permission_scope', 3, 'bot-dev-lab', 'user33', 7, 851, 'ユーザー管理とチャンネル削除の権限は使っていないため外せます。'),
    ('tech_permission_scope', 4, 'bot-dev-lab', 'user15', 7, 858, '権限を絞ったトークンへ差し替え、通常のコマンドが動くことを確認しました。'),
    ('tech_permission_scope', 5, 'bot-dev-lab', 'user07', 7, 864, '管理APIへの要求は403になりました。意図した制限が効いています。'),
    ('tech_permission_scope', 6, 'bot-dev-lab', 'user33', 7, 871, '管理APIが拒否されるところまで見てもらえたので判断できました。必要権限の一覧を設定例へ追記し、この最小構成を基準にしてよいですか？'),

    ('tech_event_dedup', 1, 'bot-dev-lab', 'user20', 10, 960, '@user02 同じイベントが二度届くと、Botが重複投稿してしまいます。'),
    ('tech_event_dedup', 2, 'bot-dev-lab', 'user02', 10, 965, 'イベントIDを処理前に記録し、既に存在するIDなら終了する形がよさそうです。'),
    ('tech_event_dedup', 3, 'bot-dev-lab', 'user33', 10, 971, '記録と処理開始を別々に行うと競合するため、一つのトランザクションに入れます。'),
    ('tech_event_dedup', 4, 'bot-dev-lab', 'user20', 10, 978, '@user33 同時に5件送る試験を追加しました。重複が出ないか確認してください。'),
    ('tech_event_dedup', 5, 'bot-dev-lab', 'user33', 10, 984, '投稿は1件だけ作成され、残り4件は処理済みとして終了しました。'),
    ('tech_event_dedup', 6, 'bot-dev-lab', 'user02', 10, 991, '同時送信の試験まで進めてもらえて助かりました。保持期間は7日を考えていますが、再送がそれより遅れる経路がないかだけ確認できますか？'),

    ('tech_payload_schema', 1, 'bot-dev-lab', 'user07', 13, 600, '@user28 新しいイベント種別でpayloadの読み込みに失敗しています。'),
    ('tech_payload_schema', 2, 'bot-dev-lab', 'user28', 13, 605, '必須扱いしていた項目が、このイベントでは省略可能になっています。'),
    ('tech_payload_schema', 3, 'bot-dev-lab', 'user20', 13, 611, '共通部分とイベント固有部分を分け、固有項目は種別ごとに検証しましょう。'),
    ('tech_payload_schema', 4, 'bot-dev-lab', 'user07', 13, 618, '分岐を追加し、未知の種別は理由をログへ出して無視するようにしました。'),
    ('tech_payload_schema', 5, 'bot-dev-lab', 'user28', 13, 624, '既存3種と新規1種のfixtureを通し、欠損時のエラーも確認できました。'),
    ('tech_payload_schema', 6, 'bot-dev-lab', 'user20', 13, 631, 'fixtureで既存種別まで確認できたので安心しました。未知の種別を無視するログ粒度も十分そうなら、このschemaでレビューへ出します。'),

    ('tech_standup_format', 1, 'bot-playground', 'user33', 2, 570, '@user15 `/standup` の結果が長く、要点を追いにくい状態です。'),
    ('tech_standup_format', 2, 'bot-playground', 'user15', 2, 574, '昨日、今日、困りごとの三項目に固定すると読み比べやすくなります。'),
    ('tech_standup_format', 3, 'bot-playground', 'user07', 2, 579, '空の項目は省略せず「なし」と表示する案で実装してみます。'),
    ('tech_standup_format', 4, 'bot-playground', 'user33', 2, 585, '@user07 三人分のサンプルを流しました。表示崩れも確認してください。'),
    ('tech_standup_format', 5, 'bot-playground', 'user07', 2, 591, '長い困りごとだけ折り返されますが、項目の順序は保たれています。'),
    ('tech_standup_format', 6, 'bot-playground', 'user15', 2, 598, '折り返し位置まで見てくれて助かります。この形式なら朝会で使えそうですが、困りごとの文字数上限はいくつが読みやすいと思いますか？'),

    ('tech_mention_guard', 1, 'bot-playground', 'user07', 5, 720, '@user33 Botが通常投稿にも反応しています。起動条件を見直したいです。'),
    ('tech_mention_guard', 2, 'bot-playground', 'user33', 5, 724, '本文にBotのユーザー名が含まれるだけで処理を始めていました。'),
    ('tech_mention_guard', 3, 'bot-playground', 'user20', 5, 729, 'Mattermostが返すmention一覧にBotのIDがある場合だけ起動しましょう。'),
    ('tech_mention_guard', 4, 'bot-playground', 'user07', 5, 735, '文字列比較をやめ、mention情報を使う判定へ変更しました。'),
    ('tech_mention_guard', 5, 'bot-playground', 'user33', 5, 741, '通常文、コード内の名前、明示mentionの三種類で期待通りに分岐します。'),
    ('tech_mention_guard', 6, 'bot-playground', 'user20', 5, 748, 'コード内の名前まで試してもらえたのが効きました。誤反応がなくなったので、この三種類を回帰試験として残す判断でよいでしょうか？'),

    ('tech_rate_limit_demo', 1, 'bot-playground', 'user20', 8, 900, '@user28 負荷試験でBotが短時間に投稿しすぎる問題を再現できました。'),
    ('tech_rate_limit_demo', 2, 'bot-playground', 'user28', 8, 904, '十件を同時送信すると、後半の要求が429になっています。'),
    ('tech_rate_limit_demo', 3, 'bot-playground', 'user33', 8, 909, '送信キューを一つにまとめ、一定間隔で取り出す方式を試しましょう。'),
    ('tech_rate_limit_demo', 4, 'bot-playground', 'user20', 8, 915, '@user33 1秒に二件までの設定で再実行をお願いします。'),
    ('tech_rate_limit_demo', 5, 'bot-playground', 'user33', 8, 922, '十件すべて成功し、順序も入力どおりに保たれました。'),
    ('tech_rate_limit_demo', 6, 'bot-playground', 'user28', 8, 929, '順序維持まで確認してくれて助かりました。待ち時間をメトリクスへ出しましたが、警告は何秒を境にするのが実運用に合いそうですか？'),

    ('tech_summary_length', 1, 'bot-playground', 'user07', 11, 1020, '@user15 長文要約が一行だけになり、決定事項が抜けています。'),
    ('tech_summary_length', 2, 'bot-playground', 'user15', 11, 1025, '結論、根拠、未決事項の三枠を明示して生成させると改善しそうです。'),
    ('tech_summary_length', 3, 'bot-playground', 'user33', 11, 1031, '入力が短い場合は枠を強制せず、そのまま短く返す条件も必要です。'),
    ('tech_summary_length', 4, 'bot-playground', 'user07', 11, 1038, '長文と短文を各三件流し、出力の長さを比較しました。'),
    ('tech_summary_length', 5, 'bot-playground', 'user15', 11, 1044, '長文では未決事項が残り、短文では余計な見出しが出ていません。'),
    ('tech_summary_length', 6, 'bot-playground', 'user33', 11, 1051, '長文と短文の差を一緒に見てもらえたので条件を絞れました。この六件を比較用サンプルに残しますが、未決事項なしの例も足した方がよいですか？'),

    ('tech_command_timeout', 1, 'bot-playground', 'user33', 14, 630, '@user02 `/report` を三回試したところ、外部処理が遅い条件では応答が返らず、利用者には処理中の表示だけが残りました。通常条件は四秒ほどで終わる一方、遅延を入れると一分後も接続が閉じません。利用者が再実行して処理を重ねる可能性があるため、待ち続ける実装は避けたいです。現在の待機上限と、中断時に子処理が残るかを確認してもらえますか？ 八秒で打ち切って再実行方法を返す案を基準に判断したいです。'),
    ('tech_command_timeout', 2, 'bot-playground', 'user02', 14, 635, '外部処理の待機上限がなく、接続が閉じるまで待ち続けています。'),
    ('tech_command_timeout', 3, 'bot-playground', 'user07', 14, 641, '8秒で処理を中断し、再実行方法を含むエラーを返すようにします。'),
    ('tech_command_timeout', 4, 'bot-playground', 'user33', 14, 648, '@user07 遅延を10秒にした条件で表示を確認してもらえますか？'),
    ('tech_command_timeout', 5, 'bot-playground', 'user07', 14, 654, '8秒で終了し、チャンネルには再試行できる案内が表示されました。'),
    ('tech_command_timeout', 6, 'bot-playground', 'user02', 14, 661, '中断後に処理が残らないことも確認できたので、試験へ追加します。'),

    ('tech_config_precedence', 1, 'dev-general', 'user02', 3, 555, '@user13 同じ設定ファイルを使っているのに、私のローカル環境だけ接続先が古い値へ戻る現象を確認しました。設定ファイルを読み直しても変わらず、起動し直した時だけ再現するため、別の設定元が上書きしているように見えます。ただし値そのものをログへ出すと機密情報まで残るので、調査方法に迷っています。環境変数や起動引数を含む優先順位を一緒に確認できますか？ 起動時には値ではなく設定元だけ記録する形が安全かも相談したいです。'),
    ('tech_config_precedence', 2, 'dev-general', 'user13', 3, 560, '設定ファイルより環境変数が優先され、古い値が残っていました。'),
    ('tech_config_precedence', 3, 'dev-general', 'user15', 3, 566, '起動時に値そのものではなく、読み込んだ設定元をログへ出しましょう。'),
    ('tech_config_precedence', 4, 'dev-general', 'user02', 3, 573, '設定元を表示したところ、不要な環境変数をすぐ特定できました。'),
    ('tech_config_precedence', 5, 'dev-general', 'user13', 3, 579, '環境変数を削除すると、設定ファイルの値で起動します。'),
    ('tech_config_precedence', 6, 'dev-general', 'user15', 3, 586, '優先順位をREADMEへ記載し、起動ログの試験も残します。'),

    ('tech_healthcheck_startup', 1, 'dev-general', 'user15', 6, 690, '@user28 起動直後だけhealth checkが失敗する現象を確認しました。'),
    ('tech_healthcheck_startup', 2, 'dev-general', 'user28', 6, 694, 'HTTPは受け付けていますが、DB接続の準備前に正常を返しています。'),
    ('tech_healthcheck_startup', 3, 'dev-general', 'user02', 6, 699, 'readinessではDB疎通まで確認し、livenessとは分けるべきです。'),
    ('tech_healthcheck_startup', 4, 'dev-general', 'user15', 6, 705, '@user02 判定を分けた版で再起動試験をお願いします。'),
    ('tech_healthcheck_startup', 5, 'dev-general', 'user02', 6, 711, '準備中はreadinessだけ失敗し、接続後に正常へ変わりました。'),
    ('tech_healthcheck_startup', 6, 'dev-general', 'user28', 6, 718, '再起動試験のおかげで境界が明確になりました。起動途中の要求は防げていますが、DB以外の依存先もreadinessへ含めるべきでしょうか？'),

    ('tech_cache_invalidation', 1, 'dev-general', 'user13', 9, 810, '@user02 更新後も古い一覧が表示される件を再現できました。'),
    ('tech_cache_invalidation', 2, 'dev-general', 'user02', 9, 815, '更新処理は成功していますが、一覧キャッシュを削除していません。'),
    ('tech_cache_invalidation', 3, 'dev-general', 'user28', 9, 821, '更新完了後に対象キーだけ消せば、全件削除を避けられます。'),
    ('tech_cache_invalidation', 4, 'dev-general', 'user13', 9, 828, '対象キーの削除を追加し、別ユーザーの一覧は保持されることも確認しました。'),
    ('tech_cache_invalidation', 5, 'dev-general', 'user02', 9, 834, '更新直後の再取得で新しい値が返り、不要なDBアクセスも増えていません。'),
    ('tech_cache_invalidation', 6, 'dev-general', 'user28', 9, 841, '別ユーザーのcacheが残ることまで確かめてもらえて助かりました。削除対象の決め方をコメントへ残し、同じ形式の更新処理にも展開してよいですか？'),

    ('tech_transaction_boundary', 1, 'dev-general', 'user28', 12, 930, '@user15 登録失敗後に関連レコードだけ残る問題が出ています。'),
    ('tech_transaction_boundary', 2, 'dev-general', 'user15', 12, 935, '本体登録と関連登録が別トランザクションになっていました。'),
    ('tech_transaction_boundary', 3, 'dev-general', 'user02', 12, 941, '二つの登録を一つにまとめ、通知処理だけcommit後へ移しましょう。'),
    ('tech_transaction_boundary', 4, 'dev-general', 'user28', 12, 948, '@user02 関連登録を意図的に失敗させる試験を追加しました。'),
    ('tech_transaction_boundary', 5, 'dev-general', 'user02', 12, 954, '失敗時は両方とも保存されず、成功時だけ通知が送られています。'),
    ('tech_transaction_boundary', 6, 'dev-general', 'user15', 12, 961, '失敗試験を用意してもらえたので、通知をcommit後へ出す理由まで確認できました。同じ形式の登録処理は、どれから点検するのがよさそうですか？'),

    ('tech_timezone_display', 1, 'dev-general', 'user02', 15, 600, '@user13 日付境界付近の履歴が前日として表示されています。'),
    ('tech_timezone_display', 2, 'dev-general', 'user13', 15, 605, '保存値はUTCですが、画面へ渡す前にもUTCの日付へ切っていました。'),
    ('tech_timezone_display', 3, 'dev-general', 'user15', 15, 611, '表示時だけ利用者のtimezoneへ変換し、保存値は変更しない形にします。'),
    ('tech_timezone_display', 4, 'dev-general', 'user02', 15, 618, '日本時間とUTCの両方で日付境界の試験を追加しました。'),
    ('tech_timezone_display', 5, 'dev-general', 'user13', 15, 624, 'どちらの設定でも期待する日付になり、並び順も変わりません。'),
    ('tech_timezone_display', 6, 'dev-general', 'user15', 15, 631, '二つのtimezoneで並び順まで見てもらえて安心しました。変換を表示層に限定するこの修正で進めますが、夏時間のfixtureも必要でしょうか？'),

    ('tech_sqlite_foreign_keys', 1, 'dev-tips', 'user15', 1, 780, '@user10 SQLiteの試験で外部キー違反が検出されない理由を確認できますか？'),
    ('tech_sqlite_foreign_keys', 2, 'dev-tips', 'user10', 1, 784, '接続ごとに外部キー検査を有効化していないことが原因です。'),
    ('tech_sqlite_foreign_keys', 3, 'dev-tips', 'user36', 1, 789, '接続直後にPRAGMAを設定し、違反データの挿入試験も追加しましょう。'),
    ('tech_sqlite_foreign_keys', 4, 'dev-tips', 'user15', 1, 795, '@user36 親がない行を入れる試験が失敗することを確認してください。'),
    ('tech_sqlite_foreign_keys', 5, 'dev-tips', 'user36', 1, 801, '期待どおり制約エラーになり、通常データはそのまま保存できました。'),
    ('tech_sqlite_foreign_keys', 6, 'dev-tips', 'user10', 1, 808, '制約違反と通常保存の両方を見てもらえて助かりました。本番と試験の接続処理を共通化しましたが、接続pool再作成時もPRAGMAが効くか確認できますか？'),

    ('tech_log_correlation', 1, 'dev-tips', 'user02', 4, 900, '@user23 一件の要求が複数サービスへ渡ると、ログを追えなくなります。'),
    ('tech_log_correlation', 2, 'dev-tips', 'user23', 4, 905, '入口で相関IDを作り、後続の要求ヘッダーへ引き継ぐ形がよさそうです。'),
    ('tech_log_correlation', 3, 'dev-tips', 'user15', 4, 911, '利用者IDとは分け、個人情報を含まないランダムなIDにしましょう。'),
    ('tech_log_correlation', 4, 'dev-tips', 'user02', 4, 918, '三つの処理で同じ相関IDが記録されるように変更しました。'),
    ('tech_log_correlation', 5, 'dev-tips', 'user23', 4, 924, 'エラー発生箇所から入口のログまで一回の検索で確認できます。'),
    ('tech_log_correlation', 6, 'dev-tips', 'user15', 4, 931, '一回の検索で入口まで追えると確認できたのが助かりました。ログ例を運用手順へ加えますが、相関IDを利用者へ返す案はどう思いますか？'),

    ('tech_flaky_test', 1, 'dev-tips', 'user36', 7, 1020, '@user28 CIで時々落ちる試験を20回実行し、3回の失敗を確認しました。'),
    ('tech_flaky_test', 2, 'dev-tips', 'user28', 7, 1025, '固定時間の待機後に結果を見るため、処理完了前に検証しています。'),
    ('tech_flaky_test', 3, 'dev-tips', 'user10', 7, 1031, '状態が変わるまで待ち、上限時間だけ固定する方式へ変えましょう。'),
    ('tech_flaky_test', 4, 'dev-tips', 'user36', 7, 1038, '@user10 修正版を50回実行しました。結果を確認してください。'),
    ('tech_flaky_test', 5, 'dev-tips', 'user10', 7, 1044, '50回すべて成功し、実行時間も以前より短くなっています。'),
    ('tech_flaky_test', 6, 'dev-tips', 'user28', 7, 1051, '50回の確認で待機方式を選ぶ根拠ができました。失敗時には最終状態も出しますが、上限時間の値はCI環境に合わせて分けるべきでしょうか？'),

    ('tech_api_pagination', 1, 'dev-tips', 'user15', 10, 570, '@user02 一覧APIで最後の一件が次のページにも重複しています。'),
    ('tech_api_pagination', 2, 'dev-tips', 'user02', 10, 575, '次ページの条件に境界値を含めているため、同じIDを再取得しています。'),
    ('tech_api_pagination', 3, 'dev-tips', 'user23', 10, 581, '時刻だけでは同値があるので、時刻とIDの組で境界を決めましょう。'),
    ('tech_api_pagination', 4, 'dev-tips', 'user15', 10, 588, '同じ時刻を持つデータを含め、三ページ分の試験を追加しました。'),
    ('tech_api_pagination', 5, 'dev-tips', 'user02', 10, 594, '重複も欠落もなく、全件を一度ずつ取得できています。'),
    ('tech_api_pagination', 6, 'dev-tips', 'user23', 10, 601, '同時刻データの試験まで作ってくれたので境界条件を決められました。cursorの形式をAPI仕様へ明記しますが、旧形式の受付期間は必要ですか？'),

    ('tech_graceful_shutdown', 1, 'dev-tips', 'user28', 13, 690, '@user15 終了時に処理中のジョブが途中で切れることがあります。'),
    ('tech_graceful_shutdown', 2, 'dev-tips', 'user15', 13, 695, '終了シグナルを受けた直後にプロセスを止めていました。'),
    ('tech_graceful_shutdown', 3, 'dev-tips', 'user02', 13, 701, '新規受付を止め、実行中のジョブを待ってから終了する順序に変えます。'),
    ('tech_graceful_shutdown', 4, 'dev-tips', 'user28', 13, 708, '@user02 30秒を超えるジョブの扱いも確認してもらえますか？'),
    ('tech_graceful_shutdown', 5, 'dev-tips', 'user02', 13, 714, '30秒で待機を打ち切り、未完了ジョブを再実行キューへ戻しました。'),
    ('tech_graceful_shutdown', 6, 'dev-tips', 'user15', 13, 721, '上限超過の扱いまで確認してもらえて助かりました。二重実行を避けるため、再実行queueへ戻す時点も試験へ含めた方がよいですか？'),

    ('tech_unread_jump', 1, 'bug-reports', 'user10', 2, 810, '@user23 未読位置から開くと末尾へ移動する問題を再現しました。'),
    ('tech_unread_jump', 2, 'bug-reports', 'user23', 2, 814, '別チャンネルから戻った直後だけ、未読位置の取得が遅れています。'),
    ('tech_unread_jump', 3, 'bug-reports', 'user36', 2, 819, '位置取得前に末尾表示が走り、その結果で状態を上書きしているようです。'),
    ('tech_unread_jump', 4, 'bug-reports', 'user10', 2, 825, '@user36 位置取得後に描画する修正版を確認してください。'),
    ('tech_unread_jump', 5, 'bug-reports', 'user36', 2, 831, '未読がある場合は最初の未読へ移動し、ない場合だけ末尾になりました。'),
    ('tech_unread_jump', 6, 'bug-reports', 'user23', 2, 838, '低速条件まで付き合ってくれて助かりました。末尾への一瞬の移動も再現しないので、この通信順序を回帰試験に固定してよいですか？'),

    ('tech_emoji_picker', 1, 'bug-reports', 'user23', 5, 930, '@user10 絵文字を連続入力すると候補一覧が閉じない問題があります。'),
    ('tech_emoji_picker', 2, 'bug-reports', 'user10', 5, 935, '確定後も検索文字列が残り、候補表示の条件を満たしていました。'),
    ('tech_emoji_picker', 3, 'bug-reports', 'user36', 5, 941, '確定時に検索文字列と選択位置を同時に初期化しましょう。'),
    ('tech_emoji_picker', 4, 'bug-reports', 'user23', 5, 948, 'マウス選択とキーボード選択の両方へ初期化を追加しました。'),
    ('tech_emoji_picker', 5, 'bug-reports', 'user10', 5, 954, '二十回連続で入力しても候補は毎回閉じ、次の入力も受け付けます。'),
    ('tech_emoji_picker', 6, 'bug-reports', 'user36', 5, 961, 'Escだけ既存動作を残す判断に迷っていましたが、操作別に確認できて整理できました。この三経路の試験でレビューへ回してよいでしょうか？'),

    ('tech_duplicate_notification', 1, 'bug-reports', 'user36', 8, 1050, '@user23 同じ投稿の通知が二回表示される事象を確認しました。'),
    ('tech_duplicate_notification', 2, 'bug-reports', 'user23', 8, 1055, '再接続時に同じイベントを履歴取得とリアルタイム受信の両方で処理しています。'),
    ('tech_duplicate_notification', 3, 'bug-reports', 'user10', 8, 1061, '投稿IDを基準に既処理判定を入れれば、受信経路が違っても除外できます。'),
    ('tech_duplicate_notification', 4, 'bug-reports', 'user36', 8, 1068, '@user10 再接続を三回繰り返す試験で確認をお願いします。'),
    ('tech_duplicate_notification', 5, 'bug-reports', 'user10', 8, 1074, '各投稿の通知は一回だけになり、新しい投稿は欠けずに表示されました。'),
    ('tech_duplicate_notification', 6, 'bug-reports', 'user23', 8, 1081, '経路順序を入れ替えても一件になる確認が助かりました。履歴とリアルタイムの境界を試験名にも明記しますが、集合の保持時間は十分でしょうか？'),

    ('tech_mobile_layout', 1, 'bug-reports', 'user10', 11, 600, '@user36 狭い画面で長いチャンネル名がボタンと重なっています。'),
    ('tech_mobile_layout', 2, 'bug-reports', 'user36', 11, 605, '名前の領域に最小幅があり、ボタン側へ縮まない設定になっています。'),
    ('tech_mobile_layout', 3, 'bug-reports', 'user23', 11, 611, '名前を省略表示にして、操作ボタンの幅を常に確保しましょう。'),
    ('tech_mobile_layout', 4, 'bug-reports', 'user10', 11, 618, '幅320と375の画面で表示を撮り直しました。'),
    ('tech_mobile_layout', 5, 'bug-reports', 'user36', 11, 624, 'どちらも重ならず、省略した名前は補足表示で全文を確認できます。'),
    ('tech_mobile_layout', 6, 'bug-reports', 'user23', 11, 631, 'focus時の補足まで確認してもらえて助かります。この修正で進めたいのですが、さらに狭い幅は非対応と明記する方がよいでしょうか？'),

    ('tech_search_stale', 1, 'bug-reports', 'user23', 14, 720, '@user10 投稿を編集した直後、チャンネル上では新しい本文になるのに、検索結果には古い本文が残る事象を三件で再現しました。十分待っても変わらず、再起動後も残るため、画面キャッシュより検索indexの更新経路を疑っています。編集API自体は成功しており、新規投稿の検索は正常です。index更新jobの失敗が記録されているか確認してもらえますか？ 再投入で直るなら、失敗を捨てず上限付きで再試行する方針にしたいです。'),
    ('tech_search_stale', 2, 'bug-reports', 'user10', 14, 725, 'DBは更新済みですが、検索インデックスの更新ジョブが失敗しています。'),
    ('tech_search_stale', 3, 'bug-reports', 'user36', 14, 731, '失敗理由を記録し、同じ投稿だけ再投入できる処理が必要です。'),
    ('tech_search_stale', 4, 'bug-reports', 'user23', 14, 738, '@user36 再投入後の検索結果と更新時刻を確認してください。'),
    ('tech_search_stale', 5, 'bug-reports', 'user36', 14, 744, '新しい本文だけが表示され、古い語では該当しなくなりました。'),
    ('tech_search_stale', 6, 'bug-reports', 'user10', 14, 751, '更新失敗の監視も追加したので、同じ停滞を検出できます。'),

    ('tech_api_latency', 1, 'incident-response', 'user23', 3, 600, '@user36 APIのp95が通常の約二倍まで上がり、直近十五分では書き込み要求に遅延が偏っています。アプリ側のエラー率はまだ低いものの、接続取得の待ち時間が同時に伸びているため、先にDB周辺を疑っています。直前の変更は集計jobの対象期間拡大だけで、利用者向け処理には触れていません。遅いqueryと接続poolの利用状況を確認してもらえますか？ 影響を止めるため、必要なら集計jobを一時停止してから恒久対応を分けて判断します。'),
    ('tech_api_latency', 2, 'incident-response', 'user36', 3, 604, '読み取りは通常値です。書き込み先DBの待機時間が増えています。'),
    ('tech_api_latency', 3, 'incident-response', 'user02', 3, 609, '直前の変更を止め、接続数と遅いqueryを確認します。'),
    ('tech_api_latency', 4, 'incident-response', 'user23', 3, 615, '@user02 遅いqueryの上位三件を共有してください。'),
    ('tech_api_latency', 5, 'incident-response', 'user02', 3, 621, '一つの集計queryが接続を占有していたため、実行を停止しました。'),
    ('tech_api_latency', 6, 'incident-response', 'user36', 3, 628, 'p95は通常値へ戻りました。query改善を恒久対応として記録します。'),

    ('tech_queue_backlog', 1, 'incident-response', 'user36', 6, 780, '@user23 通知キューの滞留が増え、処理待ちが千件を超えました。'),
    ('tech_queue_backlog', 2, 'incident-response', 'user23', 6, 785, '失敗した一件を同じworkerが繰り返し取得し、後続を止めています。'),
    ('tech_queue_backlog', 3, 'incident-response', 'user10', 6, 791, '再試行上限を超えた項目を隔離し、後続処理を再開しましょう。'),
    ('tech_queue_backlog', 4, 'incident-response', 'user36', 6, 798, '問題の一件を隔離したところ、滞留が減り始めました。'),
    ('tech_queue_backlog', 5, 'incident-response', 'user23', 6, 804, '十分後に待ち件数が通常範囲へ戻り、新規通知も処理されています。'),
    ('tech_queue_backlog', 6, 'incident-response', 'user10', 6, 811, '後続が流れ始めたことを確認してもらえて助かりました。隔離項目は原因を直してから再投入しますが、payload確認を誰と行うのがよいですか？'),

    ('tech_database_pool', 1, 'incident-response', 'user23', 9, 900, '@user02 DB接続待ちが急に増え、読み書きの両方でtimeoutが発生しています。負荷そのものは平常時と同程度ですが、利用中接続数だけが上限に張り付いたまま戻りません。直近の例外ログを追うと、特定の失敗経路を通った後から空き接続が一つずつ減っています。接続を返していない経路がないか確認してもらえますか？ まず該当処理を止めてpoolを作り直し、その後に必ず解放される構造と再現試験を入れる順で進めたいです。'),
    ('tech_database_pool', 2, 'incident-response', 'user02', 9, 905, '接続を返さない経路があり、利用可能数が徐々に減っています。'),
    ('tech_database_pool', 3, 'incident-response', 'user36', 9, 911, '該当処理を止めて接続を回収し、影響のある要求を再実行します。'),
    ('tech_database_pool', 4, 'incident-response', 'user23', 9, 918, '@user36 回収後の利用中接続数を継続監視してください。'),
    ('tech_database_pool', 5, 'incident-response', 'user36', 9, 924, '利用数は一定で推移し、timeoutも新たに発生していません。'),
    ('tech_database_pool', 6, 'incident-response', 'user02', 9, 931, '接続解放を保証する修正と、枯渇を再現する試験を追加します。'),

    ('tech_webhook_storm', 1, 'incident-response', 'user10', 12, 1020, '@user23 外部イベントの急増でWebhook処理が通常の十倍になっています。'),
    ('tech_webhook_storm', 2, 'incident-response', 'user23', 12, 1025, '同じ対象の更新が短時間に繰り返され、すべて個別処理されています。'),
    ('tech_webhook_storm', 3, 'incident-response', 'user36', 12, 1031, '対象IDごとに最新イベントだけ残し、古い更新をまとめて除外します。'),
    ('tech_webhook_storm', 4, 'incident-response', 'user10', 12, 1038, '集約を有効にすると、処理量が通常の二倍まで下がりました。'),
    ('tech_webhook_storm', 5, 'incident-response', 'user23', 12, 1044, '遅延も解消し、最終状態は受信内容と一致しています。'),
    ('tech_webhook_storm', 6, 'incident-response', 'user36', 12, 1051, '最終状態に欠落がないところまで見てもらえたので五秒窓を選べました。集約件数を監視しますが、遅延の警告値も決めませんか？'),

    ('tech_certificate_expiry', 1, 'incident-response', 'user36', 15, 540, '@user02 内部接続で証明書期限の警告が出ています。残り日数を確認してください。'),
    ('tech_certificate_expiry', 2, 'incident-response', 'user02', 15, 545, '検証環境の証明書だけ更新対象から漏れ、残り二日でした。'),
    ('tech_certificate_expiry', 3, 'incident-response', 'user23', 15, 551, '新しい証明書を配置し、接続先を順番に再起動します。'),
    ('tech_certificate_expiry', 4, 'incident-response', 'user36', 15, 558, '@user23 再起動後の期限と接続エラーを確認してもらえますか？'),
    ('tech_certificate_expiry', 5, 'incident-response', 'user23', 15, 564, '新しい期限へ更新され、接続エラーも発生していません。'),
    ('tech_certificate_expiry', 6, 'incident-response', 'user02', 15, 571, '参照processまで確認してくれて助かりました。残り三十日の警告対象へ検証環境も加えましたが、通知先は運用チャンネルでよいですか？'),

    ('tech_token_exposure', 1, 'security-lab', 'user02', 2, 660, '@user10 デバッグログを確認したところ、新しく追加したHTTPクライアントの失敗時だけ認証ヘッダーの一部が記録されていました。値は伏せますが、形式から認証情報だと推測できるため、単なる表示上の問題ではなく漏えいとして扱うべきだと考えています。成功時のログと他のクライアントでは再現しません。共通loggerへ渡す前に機密ヘッダー自体を除外できるか確認できますか？ 影響期間を絞ったうえで、該当tokenの失効まで行う判断でよいかも相談したいです。'),
    ('tech_token_exposure', 2, 'security-lab', 'user10', 2, 665, '値を伏せる処理が、追加したHTTPクライアントには適用されていません。'),
    ('tech_token_exposure', 3, 'security-lab', 'user28', 2, 671, 'ヘッダー名で共通に除外し、値をログへ渡さない形へ変えましょう。'),
    ('tech_token_exposure', 4, 'security-lab', 'user02', 2, 678, '共通filterを追加し、過去ログの対象範囲も確認しました。'),
    ('tech_token_exposure', 5, 'security-lab', 'user10', 2, 684, '新しいログにはヘッダー名だけが残り、値は出力されていません。'),
    ('tech_token_exposure', 6, 'security-lab', 'user28', 2, 691, '影響するtokenを失効し、再発防止の試験を追加して完了にします。'),

    ('tech_replay_protection', 1, 'security-lab', 'user15', 5, 840, '@user02 正しい署名を再利用すると同じ要求が通る状態です。'),
    ('tech_replay_protection', 2, 'security-lab', 'user02', 5, 845, '署名は本文だけを検証し、時刻と一意な要求IDを見ていません。'),
    ('tech_replay_protection', 3, 'security-lab', 'user10', 5, 851, '時刻の許容範囲と処理済みIDの両方を検査する必要があります。'),
    ('tech_replay_protection', 4, 'security-lab', 'user15', 5, 858, '@user10 同じ要求を二回送る試験を追加しました。確認をお願いします。'),
    ('tech_replay_protection', 5, 'security-lab', 'user10', 5, 864, '一回目だけ成功し、二回目は再利用として拒否されました。'),
    ('tech_replay_protection', 6, 'security-lab', 'user02', 5, 871, '未来時刻まで試してもらえたので境界を決められました。要求IDの保持期間を設定へ明記しますが、許容時間の二倍で十分でしょうか？'),

    ('tech_dependency_review', 1, 'security-lab', 'user28', 8, 960, '@user15 依存パッケージ更新に破壊的変更が含まれるか確認しましょう。'),
    ('tech_dependency_review', 2, 'security-lab', 'user15', 8, 965, '認証関数の既定値が変わり、明示設定が必要になっています。'),
    ('tech_dependency_review', 3, 'security-lab', 'user02', 8, 971, '現在と同じ検証方式を設定し、更新前後の結果を比較します。'),
    ('tech_dependency_review', 4, 'security-lab', 'user28', 8, 978, '認証成功、失敗、期限切れの三条件で差分がないことを確認しました。'),
    ('tech_dependency_review', 5, 'security-lab', 'user15', 8, 984, '非推奨の呼び出しも新しい関数へ置き換わっています。'),
    ('tech_dependency_review', 6, 'security-lab', 'user02', 8, 991, '新旧fixtureの比較まで進めてもらえて判断しやすくなりました。変更点と結果を記録してこの版へ上げますが、段階反映は必要ですか？'),

    ('tech_least_privilege', 1, 'security-lab', 'user10', 11, 570, '@user28 検証用サービスが全チャンネルの閲覧権限を持っています。'),
    ('tech_least_privilege', 2, 'security-lab', 'user28', 11, 575, '利用するのはBot実験場だけなので、範囲を一つに限定できます。'),
    ('tech_least_privilege', 3, 'security-lab', 'user15', 11, 581, '専用roleを作り、投稿作成と閲覧だけを許可しましょう。'),
    ('tech_least_privilege', 4, 'security-lab', 'user10', 11, 588, '@user15 権限変更後の疎通試験をお願いします。'),
    ('tech_least_privilege', 5, 'security-lab', 'user15', 11, 594, 'Bot実験場では動作し、他チャンネルの取得は拒否されました。'),
    ('tech_least_privilege', 6, 'security-lab', 'user28', 11, 601, '通常操作と拒否経路の両方を確認してくれて助かりました。この専用roleを管理手順へ加えた後、旧tokenはすぐ失効してよいですか？'),

    ('tech_audit_log', 1, 'security-lab', 'user02', 14, 690, '@user10 権限変更の監査ログに対象チャンネルが記録されていません。'),
    ('tech_audit_log', 2, 'security-lab', 'user10', 14, 695, '利用者IDとroleだけを出し、対象IDを渡していない実装でした。'),
    ('tech_audit_log', 3, 'security-lab', 'user28', 14, 701, '変更前後のrole、対象、実行者、結果を同じ記録へ入れましょう。'),
    ('tech_audit_log', 4, 'security-lab', 'user02', 14, 708, '成功と権限不足の両方で監査項目を確認しました。'),
    ('tech_audit_log', 5, 'security-lab', 'user10', 14, 714, '失敗時にも対象と実行者が残り、秘密情報は含まれていません。'),
    ('tech_audit_log', 6, 'security-lab', 'user28', 14, 721, '失敗時にも対象を追える確認が特に助かりました。監査query例を更新しますが、保持期間を過ぎた記録の扱いも併記しますか？'),

    ('tech_staging_smoke', 1, 'release-notes', 'user14', 3, 780, '@user02 ステージングへの反映が終わったので、smoke testをお願いしたいです。今回の変更は通知設定の保存処理ですが、共通APIにも手を入れているため、ログイン、投稿、検索まで確認範囲へ含めるか迷っています。反映ログにはエラーがなく、DB migrationも完了しています。まず四操作を順に試し、画面差分と新しいerror logの有無を見てもらえますか？ 問題がなければ本番反映可とし、結果をリリース記録へ残す判断にします。'),
    ('tech_staging_smoke', 2, 'release-notes', 'user02', 3, 785, 'ログイン、投稿、検索の三操作を順番に確認します。'),
    ('tech_staging_smoke', 3, 'release-notes', 'user15', 3, 791, '今回変更した通知設定も一件追加して確認しましょう。'),
    ('tech_staging_smoke', 4, 'release-notes', 'user14', 3, 798, '@user15 通知設定を含む四項目の結果をここへまとめてください。'),
    ('tech_staging_smoke', 5, 'release-notes', 'user15', 3, 804, '四項目すべて成功し、ログにも新しいエラーはありません。'),
    ('tech_staging_smoke', 6, 'release-notes', 'user02', 3, 811, '本番反映前の確認を完了として、結果をリリース記録へ添付します。'),

    ('tech_rollback_drill', 1, 'release-notes', 'user27', 6, 900, '@user15 ロールバック手順を本番反映前に通しておきたいです。'),
    ('tech_rollback_drill', 2, 'release-notes', 'user15', 6, 905, '一つ前の版へ戻し、DB変更が残っても動くことを確認します。'),
    ('tech_rollback_drill', 3, 'release-notes', 'user02', 6, 911, '戻した後のhealth checkと主要APIも試験対象に入れましょう。'),
    ('tech_rollback_drill', 4, 'release-notes', 'user27', 6, 918, '切り戻しは三分で完了し、主要APIも正常に応答しました。'),
    ('tech_rollback_drill', 5, 'release-notes', 'user15', 6, 924, '再度新しい版へ進めてもデータ差分は発生していません。'),
    ('tech_rollback_drill', 6, 'release-notes', 'user02', 6, 931, '二回の切替を同じ手順で確認できたのが助かりました。所要時間と確認項目を残しましたが、本番では誰を判断者にするか決めませんか？'),

    ('tech_migration_order', 1, 'release-notes', 'user40', 9, 1020, '@user28 次回リリースにDB migrationが含まれるため、アプリ更新との順序を確認したいです。差分は既存tableへのnullable列追加だけで、旧アプリはその列を参照しません。一方、新版は起動時から列の存在を前提にするため、アプリを先に出すと短時間でも失敗しそうです。旧版と新DBの組み合わせが本当に動くか結合試験をお願いできますか？ 結果を見て、DB更新、確認query、アプリ更新の順へ固定するか判断します。'),
    ('tech_migration_order', 2, 'release-notes', 'user28', 9, 1025, '新しい列は追加だけなので、先にmigrationしても旧版は動作します。'),
    ('tech_migration_order', 3, 'release-notes', 'user15', 9, 1031, '旧版、新DBと新版、新DBの両方を試し、互換性を確認しましょう。'),
    ('tech_migration_order', 4, 'release-notes', 'user40', 9, 1038, '@user15 二つの組み合わせで結合試験をお願いします。'),
    ('tech_migration_order', 5, 'release-notes', 'user15', 9, 1044, 'どちらも成功し、新しい列がない旧DBだけ新版で拒否されました。'),
    ('tech_migration_order', 6, 'release-notes', 'user28', 9, 1051, 'DBを先に更新する手順と、確認queryをリリース手順へ追加します。'),

    ('tech_canary_metrics', 1, 'release-notes', 'user14', 12, 570, '@user23 canary反映後の監視項目を確認してもらえますか？'),
    ('tech_canary_metrics', 2, 'release-notes', 'user23', 12, 575, 'エラー率、p95、再試行回数を旧版と並べて見ています。'),
    ('tech_canary_metrics', 3, 'release-notes', 'user02', 12, 581, '利用量が少ないため、最低百件の要求を通してから判断しましょう。'),
    ('tech_canary_metrics', 4, 'release-notes', 'user14', 12, 588, '百二十件を処理し、三項目とも旧版と同じ範囲です。'),
    ('tech_canary_metrics', 5, 'release-notes', 'user23', 12, 594, '新しい警告もなく、canary固有の失敗は確認されていません。'),
    ('tech_canary_metrics', 6, 'release-notes', 'user02', 12, 601, '百二十件まで待って比較してくれたので判断材料が揃いました。全体反映へ進め、同じ三指標を三十分見る方針でよいでしょうか？'),

    ('tech_release_notes', 1, 'release-notes', 'user27', 15, 690, '@user14 リリースノート案を読んだところ、内部module名と処理方式の説明が先に並び、利用者が何を確認すべきか掴みにくいと感じました。実際の変化は通知設定が保持されることと検索応答の改善で、操作手順は変わりません。既知の制約も一件あるため、単に「改善しました」とまとめるのは避けたいです。変更点、利用者への影響、制約、問い合わせ先の順へ組み替えてもらえますか？ 技術差分は開発記録へ分ける方針でよいかも確認したいです。'),
    ('tech_release_notes', 2, 'release-notes', 'user14', 15, 695, '利用者が変化を感じる通知設定と検索速度を先に書きます。'),
    ('tech_release_notes', 3, 'release-notes', 'user15', 15, 701, '既知の制約と、問題が起きた場合の連絡先も必要です。'),
    ('tech_release_notes', 4, 'release-notes', 'user27', 15, 708, '@user15 技術用語を減らした案をレビューしてください。'),
    ('tech_release_notes', 5, 'release-notes', 'user15', 15, 714, '操作への影響が先に分かり、制約も具体的に読める内容になっています。'),
    ('tech_release_notes', 6, 'release-notes', 'user14', 15, 721, 'この文面を公開版に使い、詳細な実装差分は開発記録へ分けます。');

COMMIT;
