PRAGMA foreign_keys = ON;
BEGIN;

DELETE FROM channel_conversation_thread_replies
WHERE conversation_id LIKE 'tech\_%' ESCAPE '\';

INSERT INTO channel_conversation_thread_replies
    (conversation_id, root_step_order, reply_order, username, offset_minutes, message)
VALUES
    ('tech_webhook_signature', 1, 1, 'user02', 1, '送信側は受信前の本文をそのまま使って署名しているとのことです。'),
    ('tech_webhook_signature', 1, 2, 'user15', 3, '受信後にJSONを整形すると空白が変わるため、同じdigestにはなりません。'),
    ('tech_webhook_signature', 1, 3, 'user02', 5, '受信したbyte列を保存して比較すると、改行が一つ削られていました。'),
    ('tech_webhook_signature', 1, 4, 'user15', 8, 'parse前の本文でHMACを計算するよう、処理順を入れ替えましょう。'),
    ('tech_webhook_signature', 1, 5, 'user02', 12, '修正版では正しい要求だけが通り、本文を変えた要求は拒否されます。'),
    ('tech_webhook_signature', 1, 6, 'user15', 17, '比較は一定時間で行う関数を使っているため、実装上の差もありません。'),
    ('tech_webhook_signature', 1, 7, 'user02', 23, '生本文と検証結果を秘密値なしで記録し、この条件を回帰試験にします。'),

    ('tech_retry_backoff', 1, 1, 'user28', 1, '現在の実装では失敗直後に三回続けて要求を送っています。'),
    ('tech_retry_backoff', 1, 2, 'user33', 3, '応答にRetry-Afterがある場合は、その秒数を最優先にしたいです。'),
    ('tech_retry_backoff', 1, 3, 'user28', 5, 'ヘッダーがない場合だけ指数backoffを使う分岐にしましょう。'),
    ('tech_retry_backoff', 1, 4, 'user33', 8, '同時に再開しないよう、待機へ小さな揺らぎも加えます。'),
    ('tech_retry_backoff', 1, 5, 'user28', 12, '最大五回、待機上限三十秒の条件でfixtureを作りました。'),
    ('tech_retry_backoff', 1, 6, 'user33', 17, '四回目で成功し、各要求の間隔も指定どおりに延びています。'),
    ('tech_retry_backoff', 1, 7, 'user28', 23, '最終失敗時は元のstatusを返すことも確認できたので、この条件で確定します。'),

    ('tech_permission_scope', 1, 1, 'user07', 1, 'Botの処理一覧から、実際に呼ぶAPIを先に洗い出します。'),
    ('tech_permission_scope', 1, 2, 'user33', 3, '投稿作成とリアクション追加のほかは、チャンネル情報の参照だけでした。'),
    ('tech_permission_scope', 1, 3, 'user07', 5, 'ユーザー管理権限を外したtokenを検証環境へ設定しました。'),
    ('tech_permission_scope', 1, 4, 'user33', 8, '通常のコマンドは成功し、管理APIへの要求は拒否されています。'),
    ('tech_permission_scope', 1, 5, 'user07', 12, '対象外チャンネルの履歴も取得できないことを確認しました。'),
    ('tech_permission_scope', 1, 6, 'user33', 17, '権限不足時のエラーはBot側で利用者向けの説明へ変換されています。'),
    ('tech_permission_scope', 1, 7, 'user07', 23, '必要なscopeと確認手順を設定資料へ追加し、広いtokenは失効します。'),

    ('tech_event_dedup', 1, 1, 'user02', 1, '配信側は応答が遅いと同じイベントIDで再送する仕様です。'),
    ('tech_event_dedup', 1, 2, 'user33', 3, '本文の一致ではなく、イベントIDを一意制約へ使うのが安全です。'),
    ('tech_event_dedup', 1, 3, 'user02', 5, '記録と処理開始の間に別workerが入らないよう、DBで確保しましょう。'),
    ('tech_event_dedup', 1, 4, 'user33', 8, 'IDのinsertに成功したworkerだけが後続処理へ進む形にしました。'),
    ('tech_event_dedup', 1, 5, 'user02', 12, '同じIDを十件並行送信しても、投稿は一件だけ作られています。'),
    ('tech_event_dedup', 1, 6, 'user33', 17, '処理失敗時は状態を失敗へ更新し、明示的な再実行だけ許可します。'),
    ('tech_event_dedup', 1, 7, 'user02', 23, '成功、重複、失敗後再実行の三経路を試験へ固定します。'),

    ('tech_payload_schema', 1, 1, 'user28', 1, '失敗したpayloadではactor項目がなく、代わりにsystemが入っています。'),
    ('tech_payload_schema', 1, 2, 'user20', 3, '共通structへ全項目を詰める設計では、この差を表現できません。'),
    ('tech_payload_schema', 1, 3, 'user28', 5, '種別を先に読み、対応するschemaへ分岐して検証しましょう。'),
    ('tech_payload_schema', 1, 4, 'user20', 8, '未知の種別は処理せず、種別名だけを警告ログへ残す形にします。'),
    ('tech_payload_schema', 1, 5, 'user28', 12, '四種類のfixtureで必須項目と省略項目を確認できました。'),
    ('tech_payload_schema', 1, 6, 'user20', 17, '既存種別の出力は変更前と同じで、互換性も保たれています。'),
    ('tech_payload_schema', 1, 7, 'user28', 23, '新しい種別を足す手順をまとめ、schema追加時の試験漏れを防ぎます。'),

    ('tech_standup_format', 1, 1, 'user15', 1, '今の出力は文章が連続し、誰の困りごとか判別しにくいです。'),
    ('tech_standup_format', 1, 2, 'user07', 3, '利用者名の見出しと三項目を固定順で出す案を作ります。'),
    ('tech_standup_format', 1, 3, 'user15', 5, '困りごとだけはmentionを残すと、担当者が気づきやすくなります。'),
    ('tech_standup_format', 1, 4, 'user07', 8, '空欄を「なし」と表示し、項目自体は省略しない形にしました。'),
    ('tech_standup_format', 1, 5, 'user15', 12, '三人分を並べても見出し単位で区切られ、読み飛ばしやすいです。'),
    ('tech_standup_format', 1, 6, 'user07', 17, '長文だけ最大文字数で切り、元投稿へのリンクを添えています。'),
    ('tech_standup_format', 1, 7, 'user15', 23, '朝会用の例で確認できたので、この出力形式を採用します。'),

    ('tech_mention_guard', 1, 1, 'user33', 1, '通常文にBot名を書いただけでも、文字列検索が一致しています。'),
    ('tech_mention_guard', 1, 2, 'user20', 3, 'コード例に含まれる名前まで起動対象になるのは避けたいです。'),
    ('tech_mention_guard', 1, 3, 'user33', 5, '投稿metadataのmention IDを参照すれば、表示文字列へ依存しません。'),
    ('tech_mention_guard', 1, 4, 'user20', 8, 'mention IDがBotと一致する場合だけ処理を始めるよう変更しました。'),
    ('tech_mention_guard', 1, 5, 'user33', 12, '通常文とコード内の名前では沈黙し、明示mentionだけ応答します。'),
    ('tech_mention_guard', 1, 6, 'user20', 17, '編集でmentionが外れた場合も、新しい処理は起動しません。'),
    ('tech_mention_guard', 1, 7, 'user33', 23, '三種類の入力を回帰試験へ残し、誤反応の修正を完了します。'),

    ('tech_rate_limit_demo', 1, 1, 'user28', 1, '一秒以内に十件送り、八件目から429になることを確認しました。'),
    ('tech_rate_limit_demo', 1, 2, 'user33', 3, '送信前に共通queueへ入れ、並列送信を止めるのがよさそうです。'),
    ('tech_rate_limit_demo', 1, 3, 'user28', 5, '一秒二件のtoken bucketで取り出す実装を試します。'),
    ('tech_rate_limit_demo', 1, 4, 'user33', 8, '待機中の件数と最古の待ち時間をmetricへ追加しました。'),
    ('tech_rate_limit_demo', 1, 5, 'user28', 12, '同じ十件はすべて成功し、送信順序も変わっていません。'),
    ('tech_rate_limit_demo', 1, 6, 'user33', 17, 'queue上限を超えた場合は、受け付けず理由を返すようにします。'),
    ('tech_rate_limit_demo', 1, 7, 'user28', 23, '成功、待機、上限超過を確認できたので負荷試験を保存します。'),

    ('tech_summary_length', 1, 1, 'user15', 1, '現在の指示では短くすることだけを優先し、未決事項を落としています。'),
    ('tech_summary_length', 1, 2, 'user33', 3, '結論、根拠、未決事項を別項目で要求すると比較しやすいです。'),
    ('tech_summary_length', 1, 3, 'user15', 5, '入力に未決事項がない場合は「なし」と明示させましょう。'),
    ('tech_summary_length', 1, 4, 'user33', 8, '会議記録三件で新旧の出力を並べ、欠落を確認しました。'),
    ('tech_summary_length', 1, 5, 'user15', 12, '新しい出力は決定事項を保ち、長さも元文の四分の一程度です。'),
    ('tech_summary_length', 1, 6, 'user33', 17, '短い入力では見出しを増やさず、一文のまま返せています。'),
    ('tech_summary_length', 1, 7, 'user15', 23, '長文と短文のfixtureを評価用に固定し、この条件で進めます。'),

    ('tech_command_timeout', 1, 1, 'user02', 1, '外部集計APIの応答待ちに上限が設定されていません。'),
    ('tech_command_timeout', 1, 2, 'user07', 3, 'コマンド受付は先に返し、集計結果を後から投稿する形も検討できます。'),
    ('tech_command_timeout', 1, 3, 'user02', 5, '今回は八秒で中断し、利用者へ再試行方法を返す仕様にしましょう。'),
    ('tech_command_timeout', 1, 4, 'user07', 8, '処理contextへtimeoutを渡し、下流の要求も同時に止めました。'),
    ('tech_command_timeout', 1, 5, 'user02', 12, '十秒遅延する条件では、八秒後に案内が表示されています。'),
    ('tech_command_timeout', 1, 6, 'user07', 17, '中断後のgoroutineと接続が残らないことも確認できました。'),
    ('tech_command_timeout', 1, 7, 'user02', 23, '正常完了とtimeoutの両経路を試験へ追加し、対応を閉じます。'),

    ('tech_config_precedence', 1, 1, 'user13', 1, '環境変数に以前の値が残り、設定ファイルを上書きしています。'),
    ('tech_config_precedence', 1, 2, 'user15', 3, '値を表示すると秘密情報が混ざるため、設定元だけをログへ出しましょう。'),
    ('tech_config_precedence', 1, 3, 'user13', 5, '起動ログへ環境変数、設定ファイル、既定値の区別を追加しました。'),
    ('tech_config_precedence', 1, 4, 'user15', 8, '問題の項目は環境変数由来と分かり、不要な定義を削除できました。'),
    ('tech_config_precedence', 1, 5, 'user13', 12, '削除後は設定ファイルの値を読み、他の項目には変化がありません。'),
    ('tech_config_precedence', 1, 6, 'user15', 17, '未定義時に既定値へ戻る経路も同じログで確認できます。'),
    ('tech_config_precedence', 1, 7, 'user13', 23, '優先順位を手順へ明記し、環境差分の調査を再現可能にします。'),

    ('tech_healthcheck_startup', 1, 1, 'user28', 1, 'HTTP listenerの開始直後に、readyを返していることが分かりました。'),
    ('tech_healthcheck_startup', 1, 2, 'user02', 3, 'DB接続とmigration完了をreadinessの条件へ含めるべきです。'),
    ('tech_healthcheck_startup', 1, 3, 'user28', 5, 'livenessはprocess応答だけにして、役割を分けましょう。'),
    ('tech_healthcheck_startup', 1, 4, 'user02', 8, '準備状態を三段階で持ち、完了後だけreadinessを成功させました。'),
    ('tech_healthcheck_startup', 1, 5, 'user28', 12, '低速なDB接続でも準備中の要求は流れ込まず、起動後に成功します。'),
    ('tech_healthcheck_startup', 1, 6, 'user02', 17, 'DB切断時はreadinessだけ失敗し、process自体は維持されています。'),
    ('tech_healthcheck_startup', 1, 7, 'user28', 23, '起動と切断の両条件を試験へ追加し、監視設定も合わせます。'),

    ('tech_cache_invalidation', 1, 1, 'user02', 1, '更新処理の後に、一覧用cacheだけが残っている状態です。'),
    ('tech_cache_invalidation', 1, 2, 'user28', 3, '全cache削除では負荷が大きいため、対象利用者のkeyだけ消しましょう。'),
    ('tech_cache_invalidation', 1, 3, 'user02', 5, '更新がcommitした後に削除し、失敗時は古いcacheを維持します。'),
    ('tech_cache_invalidation', 1, 4, 'user28', 8, '対象keyの算出を共通関数へまとめ、更新箇所の漏れを減らしました。'),
    ('tech_cache_invalidation', 1, 5, 'user02', 12, '更新直後は新しい一覧になり、別利用者のcache hitも保たれています。'),
    ('tech_cache_invalidation', 1, 6, 'user28', 17, '同時更新でも最後の値が残ることを並行試験で確認しました。'),
    ('tech_cache_invalidation', 1, 7, 'user02', 23, '対象限定の削除で要件を満たしたため、この実装を採用します。'),

    ('tech_transaction_boundary', 1, 1, 'user15', 1, '本体だけcommitした後に関連登録が失敗する経路があります。'),
    ('tech_transaction_boundary', 1, 2, 'user02', 3, '二つのrepositoryへ同じtransactionを渡せる形へ変更しましょう。'),
    ('tech_transaction_boundary', 1, 3, 'user15', 5, '通知はDB処理ではないため、commit成功後に実行するのが安全です。'),
    ('tech_transaction_boundary', 1, 4, 'user02', 8, '関連登録を失敗させると、本体もrollbackされるようになりました。'),
    ('tech_transaction_boundary', 1, 5, 'user15', 12, '成功時だけ通知が一回送られ、rollback時には送られていません。'),
    ('tech_transaction_boundary', 1, 6, 'user02', 17, 'commit後の通知失敗は再送対象として別に記録しています。'),
    ('tech_transaction_boundary', 1, 7, 'user15', 23, 'DB整合性と通知再送を分けて試験できたので、修正を確定します。'),

    ('tech_timezone_display', 1, 1, 'user13', 1, '23時台の記録だけが、UTCの日付で切られていました。'),
    ('tech_timezone_display', 1, 2, 'user15', 3, '保存と並び順はUTCのままにし、表示時だけ変換するべきです。'),
    ('tech_timezone_display', 1, 3, 'user13', 5, '日付見出しを作る直前に、利用者のtimezoneへ変換しました。'),
    ('tech_timezone_display', 1, 4, 'user15', 8, '日本時間では翌日、UTCでは前日の見出しになるfixtureを追加します。'),
    ('tech_timezone_display', 1, 5, 'user13', 12, '二つのtimezoneで期待する見出しになり、投稿順序も同じです。'),
    ('tech_timezone_display', 1, 6, 'user15', 17, '夏時間の切替があるtimezoneでも時刻の重複を処理できています。'),
    ('tech_timezone_display', 1, 7, 'user13', 23, '変換責務を表示層へ限定し、境界日の試験を固定します。'),

    ('tech_sqlite_foreign_keys', 1, 1, 'user10', 1, 'SQLiteは接続単位で外部キー検査を有効にする必要があります。'),
    ('tech_sqlite_foreign_keys', 1, 2, 'user36', 3, '本番接続では設定済みですが、試験用接続だけ抜けていました。'),
    ('tech_sqlite_foreign_keys', 1, 3, 'user10', 5, '接続生成を共通化し、最初にPRAGMAを実行するよう変更します。'),
    ('tech_sqlite_foreign_keys', 1, 4, 'user36', 8, '親がない子をinsertすると、期待する制約エラーになりました。'),
    ('tech_sqlite_foreign_keys', 1, 5, 'user10', 12, '削除時のcascadeも有効になり、孤立行は残っていません。'),
    ('tech_sqlite_foreign_keys', 1, 6, 'user36', 17, 'foreign_key_checkの結果も空で、既存fixtureは正常です。'),
    ('tech_sqlite_foreign_keys', 1, 7, 'user10', 23, '設定漏れを検出する接続試験を追加し、この問題を閉じます。'),

    ('tech_log_correlation', 1, 1, 'user23', 1, '入口のHTTP要求にはIDがありますが、queue投入時に失われています。'),
    ('tech_log_correlation', 1, 2, 'user15', 3, 'message metadataへ相関IDを入れ、workerまで渡す形にしましょう。'),
    ('tech_log_correlation', 1, 3, 'user23', 5, '外部から受けたIDは形式を検査し、不正なら新しく生成します。'),
    ('tech_log_correlation', 1, 4, 'user15', 8, 'HTTP、queue、DB更新の各ログに同じIDが記録されました。'),
    ('tech_log_correlation', 1, 5, 'user23', 12, '一つの失敗から前後の処理を検索でき、別要求とは混ざりません。'),
    ('tech_log_correlation', 1, 6, 'user15', 17, '利用者名やtokenをIDへ含めていないため、ログ共有も可能です。'),
    ('tech_log_correlation', 1, 7, 'user23', 23, '引き継ぎ境界の試験を残し、調査手順にも検索例を追加します。'),

    ('tech_flaky_test', 1, 1, 'user28', 1, '失敗時は非同期処理がまだ実行中で、結果だけ先に検証しています。'),
    ('tech_flaky_test', 1, 2, 'user10', 3, '固定sleepを延ばすのではなく、完了状態を待つ方が安定します。'),
    ('tech_flaky_test', 1, 3, 'user28', 5, '一秒上限で状態をpollし、完了時点ですぐ次へ進むようにしました。'),
    ('tech_flaky_test', 1, 4, 'user10', 8, '失敗時には最後の状態と経過時間が出るため、原因も追えます。'),
    ('tech_flaky_test', 1, 5, 'user28', 12, '五十回連続で成功し、平均実行時間は以前より短くなりました。'),
    ('tech_flaky_test', 1, 6, 'user10', 17, '処理が完了しないfixtureでは、一秒で意図どおり失敗します。'),
    ('tech_flaky_test', 1, 7, 'user28', 23, '成功とtimeoutを両方確認できたので、固定待機を削除します。'),

    ('tech_api_pagination', 1, 1, 'user02', 1, '境界の時刻を次の検索条件へ含めるため、最後の行が重複しています。'),
    ('tech_api_pagination', 1, 2, 'user23', 3, '同じ時刻の行もあるので、IDを第二sort keyに使う必要があります。'),
    ('tech_api_pagination', 1, 3, 'user02', 5, 'cursorへ時刻とIDを入れ、次は組として大きい行だけ取得します。'),
    ('tech_api_pagination', 1, 4, 'user23', 8, '同時刻五件とページ境界を含むfixtureを用意しました。'),
    ('tech_api_pagination', 1, 5, 'user02', 12, '三ページを連結すると全IDが一度ずつ現れ、欠落もありません。'),
    ('tech_api_pagination', 1, 6, 'user23', 17, '不正cursorは400にして、最初のページへ黙って戻さない形にします。'),
    ('tech_api_pagination', 1, 7, 'user02', 23, 'sort条件とcursor形式をAPI仕様へ記載し、修正を完了します。'),

    ('tech_graceful_shutdown', 1, 1, 'user15', 1, '終了シグナル受信後も、新しいジョブを受け付けていました。'),
    ('tech_graceful_shutdown', 1, 2, 'user02', 3, '先に受付を閉じ、実行中件数が零になるまで待つ順序にします。'),
    ('tech_graceful_shutdown', 1, 3, 'user15', 5, '待機上限を三十秒にして、超過分は再実行queueへ戻しましょう。'),
    ('tech_graceful_shutdown', 1, 4, 'user02', 8, '短いジョブは完了してから終了し、新規要求は拒否されています。'),
    ('tech_graceful_shutdown', 1, 5, 'user15', 12, '長いジョブは上限後にqueueへ戻り、次回起動で処理されました。'),
    ('tech_graceful_shutdown', 1, 6, 'user02', 17, '強制終了時にも二重実行にならないことをイベントIDで確認しています。'),
    ('tech_graceful_shutdown', 1, 7, 'user15', 23, '終了時の三経路を試験へ加え、運用の停止時間も更新します。'),

    ('tech_unread_jump', 1, 1, 'user23', 1, '低速条件では、未読位置取得より末尾描画が先に完了しています。'),
    ('tech_unread_jump', 1, 2, 'user36', 3, '末尾描画が既読位置を更新し、後から来た未読位置を無効にしています。'),
    ('tech_unread_jump', 1, 3, 'user23', 5, '初期位置が決まるまで、既読更新を送らないようにしましょう。'),
    ('tech_unread_jump', 1, 4, 'user36', 8, '位置取得後に一度だけ描画し、その後で既読を送る形へ変えました。'),
    ('tech_unread_jump', 1, 5, 'user23', 12, '未読あり、未読なし、削除済み投稿の三条件で移動先が正しいです。'),
    ('tech_unread_jump', 1, 6, 'user36', 17, '通信を遅らせても末尾への一瞬の移動は表示されません。'),
    ('tech_unread_jump', 1, 7, 'user23', 23, '非同期順序を固定する試験を追加し、修正版を完了にします。'),

    ('tech_emoji_picker', 1, 1, 'user10', 1, '候補確定後も検索queryがstateに残っていることを確認しました。'),
    ('tech_emoji_picker', 1, 2, 'user36', 3, '入力欄だけ消しても、選択indexが残るため再表示されます。'),
    ('tech_emoji_picker', 1, 3, 'user10', 5, '確定actionでqueryとindexを同時に初期化しましょう。'),
    ('tech_emoji_picker', 1, 4, 'user36', 8, 'マウス、Enter、Tabの三経路へ同じ初期化を適用しました。'),
    ('tech_emoji_picker', 1, 5, 'user10', 12, '各経路を連続実行しても、確定後に候補は閉じています。'),
    ('tech_emoji_picker', 1, 6, 'user36', 17, 'Escで閉じた場合は入力文字を残す既存動作も維持されています。'),
    ('tech_emoji_picker', 1, 7, 'user10', 23, '操作別の回帰試験を追加し、このUI不具合を閉じます。'),

    ('tech_duplicate_notification', 1, 1, 'user23', 1, '再接続時だけ、履歴取得とsocket受信の投稿IDが一致しています。'),
    ('tech_duplicate_notification', 1, 2, 'user10', 3, '二つの経路が別々に通知を作るため、同じIDでも重複します。'),
    ('tech_duplicate_notification', 1, 3, 'user23', 5, '通知作成前に投稿IDを共通の既処理集合へ照会しましょう。'),
    ('tech_duplicate_notification', 1, 4, 'user10', 8, '履歴を先に処理してもsocketを先に処理しても、一件だけ残ります。'),
    ('tech_duplicate_notification', 1, 5, 'user23', 12, '再接続を三回行い、古い通知は増えず新着だけ追加されました。'),
    ('tech_duplicate_notification', 1, 6, 'user10', 17, '既処理集合は一定時間で削除し、メモリが増え続けないようにしています。'),
    ('tech_duplicate_notification', 1, 7, 'user23', 23, '経路順序を入れ替える試験を残し、重複対応を完了します。'),

    ('tech_mobile_layout', 1, 1, 'user36', 1, '幅三百二十では、名前領域の最小幅がボタンを押し出しています。'),
    ('tech_mobile_layout', 1, 2, 'user23', 3, '名前側を縮め、末尾省略を許可すれば操作領域を確保できます。'),
    ('tech_mobile_layout', 1, 3, 'user36', 5, '省略時だけ補足表示を出し、全文を確認できるようにしましょう。'),
    ('tech_mobile_layout', 1, 4, 'user23', 8, '三つの画面幅でボタンが固定位置に残ることを確認しました。'),
    ('tech_mobile_layout', 1, 5, 'user36', 12, '長い日本語名と英数字名の両方で、意図した省略になっています。'),
    ('tech_mobile_layout', 1, 6, 'user23', 17, '補足表示はfocusでも開くため、キーボード操作にも対応しています。'),
    ('tech_mobile_layout', 1, 7, 'user36', 23, '表示差分をsnapshotへ追加し、狭幅の修正を確定します。'),

    ('tech_search_stale', 1, 1, 'user10', 1, '編集APIは成功していますが、index更新jobだけが失敗しています。'),
    ('tech_search_stale', 1, 2, 'user36', 3, '失敗を記録せず捨てるため、再投入する対象を特定できません。'),
    ('tech_search_stale', 1, 3, 'user10', 5, '投稿IDと失敗理由をqueueへ戻し、上限付きで再試行しましょう。'),
    ('tech_search_stale', 1, 4, 'user36', 8, '対象投稿を再投入すると、新しい本文でindexが更新されました。'),
    ('tech_search_stale', 1, 5, 'user10', 12, '古い語では該当せず、新しい語だけで検索結果へ現れます。'),
    ('tech_search_stale', 1, 6, 'user36', 17, '再試行上限を超えた投稿は監視通知へ回すようにしました。'),
    ('tech_search_stale', 1, 7, 'user10', 23, '失敗fixtureを保存し、index更新の回帰試験として使います。'),

    ('tech_api_latency', 1, 1, 'user36', 1, '書き込み先DBの待機が増え、接続取得に時間を使っています。'),
    ('tech_api_latency', 1, 2, 'user02', 3, '遅いquery一覧では、集計処理が接続を長時間保持しています。'),
    ('tech_api_latency', 1, 3, 'user36', 5, '集計jobを止め、利用者向け書き込みを優先させましょう。'),
    ('tech_api_latency', 1, 4, 'user02', 8, '停止後に接続待ちが減り、p95も下がり始めました。'),
    ('tech_api_latency', 1, 5, 'user36', 12, '五分間通常値を維持し、エラー率も増えていません。'),
    ('tech_api_latency', 1, 6, 'user02', 17, '集計queryは対象期間を分割し、読み取り専用接続へ移します。'),
    ('tech_api_latency', 1, 7, 'user36', 23, '暫定復旧と恒久対応を分けて記録し、障害対応を終了します。'),

    ('tech_queue_backlog', 1, 1, 'user23', 1, '先頭の一件が毎回失敗し、同じworkerへ戻り続けています。'),
    ('tech_queue_backlog', 1, 2, 'user10', 3, '再試行回数を確認し、上限超過を隔離queueへ移しましょう。'),
    ('tech_queue_backlog', 1, 3, 'user23', 5, '問題の一件を隔離すると、後続の処理が再開しました。'),
    ('tech_queue_backlog', 1, 4, 'user10', 8, '処理速度は通常まで戻り、待ち件数も継続して減っています。'),
    ('tech_queue_backlog', 1, 5, 'user23', 12, '隔離queueには元のpayloadと最終エラーを残しています。'),
    ('tech_queue_backlog', 1, 6, 'user10', 17, '原因を修正した後だけ手動で再投入できる操作を用意しました。'),
    ('tech_queue_backlog', 1, 7, 'user23', 23, '滞留と隔離件数の監視を追加し、今回の対応を閉じます。'),

    ('tech_database_pool', 1, 1, 'user02', 1, '一つの例外経路で、取得した接続を返さず終了しています。'),
    ('tech_database_pool', 1, 2, 'user36', 3, '処理終了時に必ずcloseする構造へ変えれば、経路ごとの差をなくせます。'),
    ('tech_database_pool', 1, 3, 'user02', 5, '該当処理を止めてpoolを再作成し、まずtimeoutを解消します。'),
    ('tech_database_pool', 1, 4, 'user36', 8, '利用可能接続が戻り、新しい要求は正常に完了しています。'),
    ('tech_database_pool', 1, 5, 'user02', 12, '例外を百回発生させても、利用中接続数は一定になりました。'),
    ('tech_database_pool', 1, 6, 'user36', 17, '接続待ち時間のmetricを追加し、枯渇前に検知できるようにします。'),
    ('tech_database_pool', 1, 7, 'user02', 23, '例外時の解放試験を残し、恒久修正としてレビューへ回します。'),

    ('tech_webhook_storm', 1, 1, 'user23', 1, '同じ対象への更新が数秒間に何十件も届いています。'),
    ('tech_webhook_storm', 1, 2, 'user36', 3, '途中状態をすべて処理せず、対象ごとの最新状態へまとめられます。'),
    ('tech_webhook_storm', 1, 3, 'user23', 5, '短い待機窓を設け、最後のイベントだけworkerへ渡しましょう。'),
    ('tech_webhook_storm', 1, 4, 'user36', 8, '五秒窓で集約すると、処理件数が十分の一まで減りました。'),
    ('tech_webhook_storm', 1, 5, 'user23', 12, '最終状態は元のイベント列と一致し、更新の欠落もありません。'),
    ('tech_webhook_storm', 1, 6, 'user36', 17, '削減件数と待機時間をmetricへ出し、遅延との均衡を見られます。'),
    ('tech_webhook_storm', 1, 7, 'user23', 23, '急増fixtureを負荷試験へ追加し、集約処理を有効にします。'),

    ('tech_certificate_expiry', 1, 1, 'user02', 1, '検証環境だけ自動更新の対象一覧から外れていました。'),
    ('tech_certificate_expiry', 1, 2, 'user23', 3, '残り二日なので、新しい証明書を先に配置して切り替えます。'),
    ('tech_certificate_expiry', 1, 3, 'user02', 5, '一台ずつ再起動し、接続を維持しながら更新しましょう。'),
    ('tech_certificate_expiry', 1, 4, 'user23', 8, '全接続先で新しい期限が返り、TLSエラーもありません。'),
    ('tech_certificate_expiry', 1, 5, 'user02', 12, '古い証明書を参照するprocessがないことも確認できました。'),
    ('tech_certificate_expiry', 1, 6, 'user23', 17, '自動更新の対象へ検証環境を追加し、次回時刻を記録しています。'),
    ('tech_certificate_expiry', 1, 7, 'user02', 23, '三十日前の警告試験を加え、期限切れ対応を完了します。'),

    ('tech_token_exposure', 1, 1, 'user10', 1, '追加したHTTPクライアントだけ、headerをそのまま記録しています。'),
    ('tech_token_exposure', 1, 2, 'user28', 3, '値をmaskするより、機密header自体をloggerへ渡さない方が安全です。'),
    ('tech_token_exposure', 1, 3, 'user10', 5, '共通filterでauthorizationとcookieを除外するよう変更しました。'),
    ('tech_token_exposure', 1, 4, 'user28', 8, '成功と失敗のログを確認し、どちらにも値は含まれていません。'),
    ('tech_token_exposure', 1, 5, 'user10', 12, '影響期間のログを限定し、該当tokenをすべて失効しました。'),
    ('tech_token_exposure', 1, 6, 'user28', 17, '機密headerをfixtureへ入れ、出力されないことを自動試験にします。'),
    ('tech_token_exposure', 1, 7, 'user10', 23, '再発防止と失効確認が終わったため、この対応を完了します。'),

    ('tech_replay_protection', 1, 1, 'user02', 1, '現在は本文と署名だけが同じなら、何度でも受理されます。'),
    ('tech_replay_protection', 1, 2, 'user10', 3, '時刻headerを署名対象へ含め、許容時間も検査しましょう。'),
    ('tech_replay_protection', 1, 3, 'user02', 5, '同じ時間内の再送には、要求IDの処理済み判定も必要です。'),
    ('tech_replay_protection', 1, 4, 'user10', 8, '時刻とIDの両検査を追加し、処理前に拒否するようにしました。'),
    ('tech_replay_protection', 1, 5, 'user02', 12, '初回は成功し、同じ要求の二回目は再利用として拒否されます。'),
    ('tech_replay_protection', 1, 6, 'user10', 17, '古い時刻と未来時刻も許容範囲外として拒否できています。'),
    ('tech_replay_protection', 1, 7, 'user02', 23, '境界時刻を含む試験を追加し、この防御を有効にします。'),

    ('tech_dependency_review', 1, 1, 'user15', 1, 'release noteでは認証関数の既定値変更が主な影響です。'),
    ('tech_dependency_review', 1, 2, 'user02', 3, '現在の検証方式を明示すれば、更新前と同じ動作を保てます。'),
    ('tech_dependency_review', 1, 3, 'user15', 5, '非推奨になった呼び出しも二か所あるため、同時に置き換えます。'),
    ('tech_dependency_review', 1, 4, 'user02', 8, '成功、署名不正、期限切れのfixtureを新旧で比較しました。'),
    ('tech_dependency_review', 1, 5, 'user15', 12, '結果はすべて一致し、警告も解消されています。'),
    ('tech_dependency_review', 1, 6, 'user02', 17, '依存先が増やしたnetwork要求もなく、性能差は測定誤差内です。'),
    ('tech_dependency_review', 1, 7, 'user15', 23, '変更点と比較結果を記録し、このversionへ更新します。'),

    ('tech_least_privilege', 1, 1, 'user28', 1, '検証用tokenはsystem管理権限まで含むroleを使っています。'),
    ('tech_least_privilege', 1, 2, 'user15', 3, '必要なのはBot実験場の閲覧と投稿だけに限定できます。'),
    ('tech_least_privilege', 1, 3, 'user28', 5, '専用roleを作り、対象チャンネルへだけ割り当てました。'),
    ('tech_least_privilege', 1, 4, 'user15', 8, '通常操作は成功し、他チャンネルと管理APIは拒否されています。'),
    ('tech_least_privilege', 1, 5, 'user28', 12, '権限不足時のログにもtoken値は出ていません。'),
    ('tech_least_privilege', 1, 6, 'user15', 17, '広いroleを外した後も、デモの操作を最後まで実行できました。'),
    ('tech_least_privilege', 1, 7, 'user28', 23, '専用roleの定義と確認手順を保存し、旧tokenを失効します。'),

    ('tech_audit_log', 1, 1, 'user10', 1, '現在の記録には実行者と新しいroleだけが入っています。'),
    ('tech_audit_log', 1, 2, 'user28', 3, '対象、変更前、変更後、結果を同じeventへ含める必要があります。'),
    ('tech_audit_log', 1, 3, 'user10', 5, '秘密値を避け、IDとrole名だけを構造化して記録しましょう。'),
    ('tech_audit_log', 1, 4, 'user28', 8, '成功、権限不足、対象なしの三経路で項目を確認しました。'),
    ('tech_audit_log', 1, 5, 'user10', 12, '失敗時にも実行者と対象が残り、原因を一件に絞れます。'),
    ('tech_audit_log', 1, 6, 'user28', 17, 'role名で検索しても、変更前後の流れを追える状態です。'),
    ('tech_audit_log', 1, 7, 'user10', 23, '監査queryの例を手順へ追加し、記録形式を確定します。'),

    ('tech_staging_smoke', 1, 1, 'user02', 1, '反映は完了しています。まずログインから順に確認します。'),
    ('tech_staging_smoke', 1, 2, 'user15', 3, '今回の変更対象である通知設定も確認項目へ入れてください。'),
    ('tech_staging_smoke', 1, 3, 'user02', 5, 'ログインと投稿は成功し、検索にも新しい投稿が現れました。'),
    ('tech_staging_smoke', 1, 4, 'user15', 8, '通知設定を変更して再読み込みしても、選択した値が維持されています。'),
    ('tech_staging_smoke', 1, 5, 'user02', 12, '四操作の間に新しいerror logは記録されていません。'),
    ('tech_staging_smoke', 1, 6, 'user15', 17, '前版との画面差分も今回の変更範囲だけでした。'),
    ('tech_staging_smoke', 1, 7, 'user02', 23, '結果をリリース記録へ添付し、本番反映可能として返します。'),

    ('tech_rollback_drill', 1, 1, 'user15', 1, '一つ前のimageと現在のDBを組み合わせて切り戻します。'),
    ('tech_rollback_drill', 1, 2, 'user02', 3, '今回のDB変更は列追加だけなので、旧版も読み込める想定です。'),
    ('tech_rollback_drill', 1, 3, 'user15', 5, '切替前に処理中jobを止め、完了件数を記録しておきます。'),
    ('tech_rollback_drill', 1, 4, 'user02', 8, '旧版は三分で起動し、health checkと投稿APIが成功しました。'),
    ('tech_rollback_drill', 1, 5, 'user15', 12, '新しい版へ戻しても、切替中のデータ欠落はありません。'),
    ('tech_rollback_drill', 1, 6, 'user02', 17, '二回の切替で同じ手順を使え、手作業の追加も不要でした。'),
    ('tech_rollback_drill', 1, 7, 'user15', 23, '所要時間と確認結果を記録し、切り戻し手順を確定します。'),

    ('tech_migration_order', 1, 1, 'user28', 1, 'migrationは既存tableへのnullable列追加だけになっています。'),
    ('tech_migration_order', 1, 2, 'user15', 3, '旧アプリは列を参照しないため、DBを先に更新しても動作します。'),
    ('tech_migration_order', 1, 3, 'user28', 5, '新版は列の存在を前提にするので、アプリ先行は避けるべきです。'),
    ('tech_migration_order', 1, 4, 'user15', 8, '旧版と新DB、新版と新DBの二組で結合試験を行いました。'),
    ('tech_migration_order', 1, 5, 'user28', 12, '二組とも成功し、旧DBと新版の組だけは起動前検査で止まります。'),
    ('tech_migration_order', 1, 6, 'user15', 17, '確認queryを手順へ入れれば、順序違反を反映前に検出できます。'),
    ('tech_migration_order', 1, 7, 'user28', 23, 'DB更新、確認、アプリ更新の順でリリース手順を固定します。'),

    ('tech_canary_metrics', 1, 1, 'user23', 1, 'canaryは全体の一割へ反映され、要求数はまだ三十件です。'),
    ('tech_canary_metrics', 1, 2, 'user02', 3, '判断には少ないため、百件を超えるまで同じ指標を見ましょう。'),
    ('tech_canary_metrics', 1, 3, 'user23', 5, 'エラー率、p95、再試行回数を旧版と並べて監視します。'),
    ('tech_canary_metrics', 1, 4, 'user02', 8, '百二十件まで増えましたが、三指標に有意な差はありません。'),
    ('tech_canary_metrics', 1, 5, 'user23', 12, '新しい警告もなく、利用者からの失敗報告も出ていません。'),
    ('tech_canary_metrics', 1, 6, 'user02', 17, '全体反映後も三十分は同じdashboardを継続して確認します。'),
    ('tech_canary_metrics', 1, 7, 'user23', 23, '判断条件を満たしたため、canary確認を完了として共有します。'),

    ('tech_release_notes', 1, 1, 'user14', 1, '現在の案は内部のmodule名が多く、利用者の変化が後ろにあります。'),
    ('tech_release_notes', 1, 2, 'user15', 3, '通知設定と検索速度の改善を先頭へ置くと、影響を判断しやすいです。'),
    ('tech_release_notes', 1, 3, 'user14', 5, '操作手順が変わらない点と、既知の制約も続けて記載します。'),
    ('tech_release_notes', 1, 4, 'user15', 8, '内部実装の詳細は開発記録へ移し、公開文からは外しました。'),
    ('tech_release_notes', 1, 5, 'user14', 12, '変更点、影響、制約、問い合わせ先の順で読める内容になっています。'),
    ('tech_release_notes', 1, 6, 'user15', 17, '曖昧な改善表現を数値と具体的な操作へ置き換えました。'),
    ('tech_release_notes', 1, 7, 'user14', 23, '利用者向け文面として確定し、技術差分とは別に公開します。');

COMMIT;
